# Анализ влияния погодных условий на ДТП

## Цель и задачи проекта
**Цель**: сбор погодных данных и данных о ДТП для выбранных городов в Российской Федерации и проведение анализа для 
выявления взаимосвязей между ними.

**Задачи данного этапа**:
- Загрузка ключевых данных: 
-- Список городов РФ;
-- Координаты городов;
-- Коды ОКАТО регионов РФ;
-- Данные о погоде;
-- Карточки ДТП;
- Проведение очистки и предобработки данных;
- Загрузка данных в базу данных.

## Содержание:
1. [Парсинг списка городов со страницы Википедии](#soderjanie_1)
2. [Создание соединения к базе данных](#soderjanie_2)
3. [Предобработка и обогащение данных (геокодирование (добавление координат)) о городах РФ и их выгрузка в таблицу базы данных](#soderjanie_3)
4. [Парсинг данных о погоде через API](#soderjanie_4)
5. [Предобработка данных о погоде в выбранных городах и выгрузка в таблицу базы данных](#soderjanie_5)
6. [Получение ОКАТО-кодов регионов РФ](#soderjanie_6)
7. [Предобработка данных о кодах ОКАТО и их выгрузка в таблицу базы данных](#soderjanie_7)
8. [Парсинг данных о ДТП через API](#soderjanie_8)
9. [Предобработка данных о ДТП и их выгрузка в таблицу базы данных](#soderjanie_9)
10. [Выводы](#soderjanie_10)

## 1. Парсинг списка городов со страницы Википедии <a id='soderjanie_1'></a>

In [1]:
#Устанавливаем библиотеки

!pip install geopy
!pip install requests_cache

Requirement already satisfied: geopy in /opt/conda/lib/python3.9/site-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in /opt/conda/lib/python3.9/site-packages (from geopy) (2.1)
Requirement already satisfied: requests_cache in /opt/conda/lib/python3.9/site-packages (1.3.1)
Requirement already satisfied: urllib3>=1.25.5 in /opt/conda/lib/python3.9/site-packages (from requests_cache) (1.26.6)
Requirement already satisfied: url-normalize>=2.0 in /opt/conda/lib/python3.9/site-packages (from requests_cache) (2.2.1)
Requirement already satisfied: cattrs>=22.2 in /opt/conda/lib/python3.9/site-packages (from requests_cache) (25.3.0)
Requirement already satisfied: platformdirs>=2.5 in /opt/conda/lib/python3.9/site-packages (from requests_cache) (4.4.0)
Requirement already satisfied: requests>=2.22 in /opt/conda/lib/python3.9/site-packages (from requests_cache) (2.32.5)
Requirement already satisfied: attrs>=21.2 in /opt/conda/lib/python3.9/site-packages (from requests_cache) (25.4.0)
Requirement already satisfied: exceptiongroup>=1.1.1 in /opt/conda/lib/python3.9/site-packages (from cattrs>=22.2->requests_cache) (1.3.1)
Requirement already satisfied: typing-extensions>=4.14.0 in /opt/conda/lib/python3.9/site-packages (from cattrs>=22.2->requests_cache) (4.15.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.9/site-packages (from requests>=2.22->requests_cache) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.9/site-packages (from requests>=2.22->requests_cache) (2022.6.15)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.9/site-packages (from requests>=2.22->requests_cache) (3.4.5)

In [2]:
#Импортируем библиотеки

import requests
import requests_cache
import pandas as pd
import numpy as np
import logging
from bs4 import BeautifulSoup
from tqdm import tqdm
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
from typing import List, Optional
import json
import time
from datetime import datetime
import sqlalchemy

In [3]:
#Сохраняем список выбранных городов

cities_selected=['Казань','Новосибирск']

In [4]:
#Функция для логирования

def setup_logging() -> logging.Logger:

    '''Настройка логирования.'''

    log_filename = f'common.log'  # Название файла логов

    logger = logging.getLogger('dtp_weather') # Название логера
    logger.setLevel(logging.INFO)

    # Очистка существующих обработчиков
    if logger.handlers:
        logger.handlers.clear()

    # Обработчик для файла
    file_handler = logging.FileHandler(log_filename, encoding='utf-8')
    # Формат вывода сообщений логов в файл
    file_formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    file_handler.setFormatter(file_formatter)
    logger.addHandler(file_handler)

    # Обработчик для консоли
    console_handler = logging.StreamHandler()
    # Формат вывода логов в консоль (сокращенный)
    console_formatter = logging.Formatter('%(levelname)s: %(message)s')
    console_handler.setFormatter(console_formatter)
    logger.addHandler(console_handler)

    return logger

In [5]:
#Функция для получения HTML-кода страницы по заданному URL

def get_html(url: str,
             headers: str) -> str:

    '''Получает HTML-код страницы по заданному URL.'''

    try:
        logger.info(f'Попытка получить HTML-код страницы: {url}')
        response = requests.get(url, headers=headers, timeout=10)
        response.raise_for_status()  # Проверка на ошибки HTTP
        logger.info('HTML-код успешно получен.')
        return response.text
    except requests.exceptions.RequestException as e:
        logger.error(f'Ошибка при получении HTML-кода: {e}')
        raise

In [6]:
#Функция для получения таблицы с административными центрами из HTML-кода

def parse_table(html: str) -> list:

    '''Парсит таблицу с административными центрами из HTML-кода.'''

    try:
        logger.info('Парсинг HTML-кода для извлечения таблицы.')
        soup = BeautifulSoup(html, 'html.parser')
        table = soup.find('table')

        if not table:
            logger.error('Таблица не найдена на странице.')
            raise ValueError('Таблица не найдена.')

        rows = table.find_all('tr')
        if not rows:
            logger.error('Строки таблицы не найдены.')
            raise ValueError('Строки таблицы не найдены.')

        data = []

        for row in rows:
            cols = row.find_all('td')
            cols = [col.text.strip() for col in cols]
            data.append(cols)

        logger.info(f'Успешно извлечено {len(data)} строк из таблицы.')
        return data
    except Exception as e:
        logger.error(f'Ошибка при парсинге таблицы: {e}')
        raise

In [7]:
#Функция для сохрания данных в датафрейм и CSV-файл

def save_to_csv_DataFrame(data: list, filename: str) -> None:

    '''Сохраняет данные в датафрейм и CSV-файл'''
    try:
        logger.info(f'Сохранение данных в датафрейм и файл: {filename}')
        columns = [
            'num',
            'coat_of_arms',
            'city_name',
            'region',
            'federal',
            'population',
            'foundation_or_first_mention',
            'year_of_city_status',
            'former_city_name'
        ]

        df = pd.DataFrame(data[1:], columns=columns)
        df.to_csv(filename, index=False, encoding='utf-8')
        logger.info(f'Данные успешно сохранены в датафрейм и файл: {filename}')
        return df
    except Exception as e:
        logger.error(f'Ошибка при сохранении данных в датафрейм и CSV: {e}')
        raise

In [8]:
#Выполняем функции для получения списка городов и сохранения их в датафрейм и в файл

if __name__ =='__main__':  # этот блок кода работает, когда файл запущен напрямую
    # Сохраняем строкy подключения к русской Википедии
    url_cities = 'https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D0%BE%D0%B2_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8'
    
    # Указываем заголовок
    user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36'
    headers = {'User-Agent': user_agent}
    
    # Указываем имя файла
    output_filename = 'cities_rf.csv'
    
    # Создаем логер
    logger = setup_logging()
     
    #Выполняем функции
    try:
        html_city = get_html(url_cities, headers)
        data_city = parse_table(html_city)
        df_city = save_to_csv_DataFrame(data_city, output_filename)
        
    except Exception as e:
        logger.error(f"Ошибка в процессе выполнения скрипта: {e}")

INFO: Попытка получить HTML-код страницы: https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D0%BE%D0%B2_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8
INFO: HTML-код успешно получен.
INFO: Парсинг HTML-кода для извлечения таблицы.
INFO: Успешно извлечено 1126 строк из таблицы.
INFO: Сохранение данных в датафрейм и файл: cities_rf.csv
INFO: Данные успешно сохранены в датафрейм и файл: cities_rf.csv

_____

## 2. Создание соединения к базе данных <a id='soderjanie_2'></a>

In [9]:
# Параметры базы данных

USER ='postgres.pkhitenuyhdiohvrxklz'
PASSWORD = 'Stop_Start_7'
HOST = 'aws-1-eu-central-2.pooler.supabase.com'
PORT = '6543'
DBNAME = 'postgres'

In [10]:
# Сформируем строку подключения к SQLAlchemy

DATABASE_URL = f"postgresql+psycopg2://{USER}:{PASSWORD}@{HOST}:{PORT}/{DBNAME}?sslmode=require"

In [11]:
# Создаем соединение

engine = sqlalchemy.create_engine(DATABASE_URL)
logger.info("Создаем подключение к базе данных")

INFO: Создаем подключение к базе данных

In [13]:
# Tест соединения

try:
    with engine.connect() as connection:
        logger.info("Connection successful!")
except Exception as e:
    logger.error(f"Failed to connect: {e}")

INFO: Connection successful!

___

## 3. Предобработка и обогащение данных (геокодирование (добавление координат)) о городах РФ и их выгрузка в таблицу базы данных <a id='soderjanie_3'></a>

In [ ]:
#Выгружаем полученные данные о городах в буферную таблицу базы данных

logger.info("Выгружаем полученные данные о городах в буферную таблицу базы данных")
df_city.to_sql('bufer_cities', con=engine, if_exists='replace', index=False)
logger.info("Данные о городах успешно выгружены в буферную таблицу базы данных")

In [14]:
# Выводим информацию о датафрейме

df_city.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   num                          1125 non-null   object
 1   coat_of_arms                 1125 non-null   object
 2   city_name                    1125 non-null   object
 3   region                       1125 non-null   object
 4   federal                      1125 non-null   object
 5   population                   1125 non-null   object
 6   foundation_or_first_mention  1125 non-null   object
 7   year_of_city_status          1125 non-null   object
 8   former_city_name             1125 non-null   object
dtypes: object(9)
memory usage: 79.2+ KB

In [15]:
# Выводим первые 5 строк датафрейма с городами

df_city.head()

,num,coat_of_arms,city_name,region,federal,population,foundation_or_first_mention,year_of_city_status,former_city_name
0,1,,Абаза,Хакасия,Сибирский,12 272,1867,1966,"Абаканский Завод, Абаканско-Заводское"
1,2,,Абакан,Хакасия,Сибирский,184 769,1734,1931,Усть-Абаканское (до 1931)
2,3,,Абдулино,Оренбургская область,Приволжский,17 274,1795,1923,
3,4,,Абинск,Краснодарский край,Южный,39 511,1863,1963,Абинское (до 1863);Абинская (до 1962)
4,5,,Агидель,Башкортостан,Приволжский,14 219,1980,1991,

In [16]:
# Оставляем необходимые для работы колонки

df_city=df_city[['city_name', 'region', 'federal', 'population']]

In [17]:
# Проверяем уникальные значения федеральных округов

df_city['federal'].unique()

array(['Сибирский', 'Приволжский', 'Южный', 'Северо-Кавказский',
       'Уральский', 'Дальневосточный', 'Центральный', 'Северо-Западный'],
      dtype=object)

In [18]:
# Проверяем уникальные значения регионов

df_city['region'].unique()

array(['Хакасия', 'Оренбургская область', 'Краснодарский край',
       'Башкортостан', 'Татарстан', 'Адыгея', 'Ростовская область',
       'Тыва', 'Северная Осетия', 'Свердловская область', 'Чувашия',
       'Якутия', 'Алтайский край', 'Владимирская область',
       'Пермский край', 'Сахалинская область', 'Белгородская область',
       'Тульская область', 'Иркутская область', 'Крым',
       'Хабаровский край', 'Чукотский АО', 'Тверская область',
       'Кемеровская область', 'Мурманская область', 'Московская область',
       'Чечня', 'Мордовия', 'Нижегородская область',
       'Саратовская область', 'Приморский край', 'Красноярский край',
       'Архангельская область', 'Томская область', 'Астраханская область',
       'Челябинская область', 'Вологодская область', 'Бурятия',
       'Калининградская область', 'Кабардино-Балкария',
       'Калужская область', 'Забайкальский край', 'Новосибирская область',
       'Ульяновская область', 'Кировская область', 'Пензенская область',
       'Амурская область', 'Карелия', 'Ханты-Мансийский АО',
       'Еврейская АО', 'Ставропольский край', 'Воронежская область',
       'Ленинградская область', 'Орловская область',
       'Новгородская область', 'Брянская область', 'Костромская область',
       'Дагестан', 'Смоленская область', 'Псковская область',
       'Камчатский край', 'Ивановская область', 'Волгоградская область',
       'Марий Эл', 'Коми', 'Удмуртия', 'Ярославская область', 'Алтай',
       'Калмыкия', 'Липецкая область', 'Ямало-Ненецкий АО',
       'Курганская область', 'Курская область', 'Тамбовская область',
       'Самарская область', 'Тюменская область', 'Омская область',
       'Ингушетия', 'Карачаево-Черкесия', 'Рязанская область',
       'Магаданская область', 'Москва', 'Ненецкий АО', 'Санкт-Петербург',
       'Севастополь'], dtype=object)

In [19]:
# Преобразуем данные о названии региона

df_city['region'] = df_city['region'].str.replace('Еврейская АО', 'Еврейская Автономная область')
df_city['region'] = df_city['region'].str.replace(' АО', ' Автономный округ')

In [20]:
# Преобразуем и очистим данные о названии городов

df_city['city_name'] = df_city['city_name'].str.replace('не призн.', '').str.strip()

/tmp/ipykernel_338/2485007527.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  df_city['city_name'] = df_city['city_name'].str.replace('не призн.', '').str.strip()

In [21]:
# Преобразуем и очистим данные о населении городов

df_city['population'] = df_city['population'].str.replace(' ', '').str.split('[').str[0].astype('int')

In [22]:
# Добавляем пустые колонки для координат

df_city['lat'], df_city['lon'] = None, None

In [23]:
#Функция для получения координат по названию города через геокодер Nominatim

def coordinates(user_agent: str):

    '''
    Функция для получения координат по названию города через геокодер Nominatim.

    '''
    try:
        logger.info(f'Заполнение данных о широте и долготе в соответствующих полях датафрейма')
        geolocator = Nominatim(user_agent=user_agent)
        geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)
        for index, row in df_city.iterrows():
            state=row['region']
            city=row['city_name']
            location = geocode(f'{state}, {city}')
            if location:
                df_city.loc[index, 'lon']=location.longitude
                df_city.loc[index, 'lat']=location.latitude
            else:
                df_city.loc[index, 'lon']='Нет данных'
                df_city.loc[index, 'lat']='Нет данных'
                
        logger.info(f'Данные о широте и долготе успешно заполнены')
        return df_city
    except Exception as e:
        logger.error(f'Ошибка при заполнении данных о широте и долготе: {e}')
        raise

In [24]:
#Выполняем функцию для сохранения обогащенного датафрейма с координатами городов

user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36'
df_city = coordinates(user_agent)

INFO: Заполнение данных о широте и долготе в соответствующих полях датафрейма
INFO: Данные о широте и долготе успешно заполнены

In [25]:
# Проверяем наличие незаполненных данных

df_city[(df_city['lon']=='Нет данных')| (df_city['lat']=='Нет данных')]

Empty DataFrame
Columns: [city_name, region, federal, population, lat, lon]
Index: []

In [26]:
#Фильтруем датафрейм от незаполненных данных

df_city=df_city[(df_city['lon']!='Нет данных')& (df_city['lat']!='Нет данных')]

In [27]:
# Выводим информацию о датафрейме

df_city.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1125 entries, 0 to 1124
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   city_name   1125 non-null   object
 1   region      1125 non-null   object
 2   federal     1125 non-null   object
 3   population  1125 non-null   int64
 4   lat         1125 non-null   object
 5   lon         1125 non-null   object
dtypes: int64(1), object(5)
memory usage: 61.5+ KB

In [28]:
# Изменяем тип данных полей с координатами на float

df_city['lon'] = df_city['lon'].astype('float')
df_city['lat'] = df_city['lat'].astype('float')

In [29]:
# Применяем метод nunique() к столбцу city_name

df_city['city_name'].nunique()

1105

In [30]:
#Сохраняем и выводим значения-дубликаты по полю с названием городов

dupl_cities=df_city.loc[(df_city['city_name'].duplicated())]['city_name']
dupl_cities

86           Белогорск
99         Берёзовский
109       Благовещенск
234           Гурьевск
291       Железногорск
313           Заречный
412              Киров
416            Кировск
465      Красноармейск
471     Краснознаменск
476     Краснослободск
593             Мирный
597         Михайловск
658           Никольск
705             Озёрск
783           Приморск
801           Радужный
886            Советск
887            Советск
1026            Фокино
Name: city_name, dtype: object

In [31]:
#Выводим строки датафрейма по дублирующимся городам для проверки заполнения широты и долготиы

df_city[df_city['city_name'].isin(dupl_cities)]

,city_name,region,federal,population,lat,lon
85,Белогорск,Амурская область,Дальневосточный,61440,50.921326,128.472870
86,Белогорск,Крым,Южный,17445,45.058439,34.594959
98,Берёзовский,Кемеровская область,Сибирский,44932,55.669695,86.275154
99,Берёзовский,Свердловская область,Уральский,59698,56.909787,60.812025
108,Благовещенск,Башкортостан,Приволжский,35481,55.046236,55.961169
109,Благовещенск,Амурская область,Дальневосточный,241437,50.260042,127.533738
233,Гурьевск,Калининградская область,Северо-Западный,26760,54.774557,20.603704
234,Гурьевск,Кемеровская область,Сибирский,22134,54.284954,85.931091
290,Железногорск,Красноярский край,Сибирский,82723,56.250938,93.532860
291,Железногорск,Курская область,Центральный,97038,52.338946,35.351175
312,Заречный,Пензенская область,Приволжский,58510,53.196014,45.169273
313,Заречный,Свердловская область,Уральский,28112,56.814971,61.320594
411,Киров,Калужская область,Центральный,28097,54.074290,34.302598
412,Киров,Кировская область,Приволжский,468212,58.603566,49.666624
415,Кировск,Ленинградская область,Северо-Западный,27238,59.881395,30.985533
416,Кировск,Мурманская область,Северо-Западный,24857,67.615133,33.663753
464,Красноармейск,Московская область,Центральный,26492,56.121089,38.145766
465,Красноармейск,Саратовская область,Приволжский,21350,51.025776,45.692520
470,Краснознаменск,Калининградская область,Северо-Западный,3419,54.941522,22.491298
471,Краснознаменск,Московская область,Центральный,43868,55.597179,37.039506
475,Краснослободск,Волгоградская область,Южный,16545,48.703905,44.555795
476,Краснослободск,Мордовия,Приволжский,8910,54.430672,43.777900
592,Мирный,Якутия,Дальневосточный,34045,62.541046,113.978516
593,Мирный,Архангельская область,Северо-Западный,27262,62.762352,40.328644
596,Михайловск,Свердловская область,Уральский,9756,56.444538,59.124191
597,Михайловск,Ставропольский край,Северо-Кавказский,114133,45.132491,42.026330
657,Никольск,Вологодская область,Северо-Западный,7661,59.530419,45.458503
658,Никольск,Пензенская область,Приволжский,19873,53.714596,46.085175
704,Озёрск,Калининградская область,Северо-Западный,4152,54.408741,22.014359
705,Озёрск,Челябинская область,Уральский,76896,55.760460,60.705101
782,Приморск,Калининградская область,Северо-Западный,1436,54.730195,20.004430
783,Приморск,Ленинградская область,Северо-Западный,6537,60.366665,28.616673
800,Радужный,Владимирская область,Центральный,17569,55.993959,40.329441
801,Радужный,Ханты-Мансийский Автономный округ,Уральский,43577,62.135315,77.462616
885,Советск,Калининградская область,Северо-Западный,38910,55.080969,21.888267
886,Советск,Кировская область,Приволжский,14626,57.586189,48.958698
887,Советск,Тульская область,Центральный,7889,53.934659,37.632086
1025,Фокино,Брянская область,Центральный,12538,53.452663,34.415459
1026,Фокино,Приморский край,Дальневосточный,19711,42.977208,132.404905

In [32]:
# Выводим первые 10 строк датафрейма, отсортированного по населению, на экран

df_city.sort_values(by='population', ascending=False).head(10)

,city_name,region,federal,population,lat,lon
607,Москва,Москва,Центральный,13010112,55.750541,37.617478
831,Санкт-Петербург,Санкт-Петербург,Северо-Западный,5601911,59.938732,30.316229
676,Новосибирск,Новосибирская область,Сибирский,1633595,55.028831,82.922689
277,Екатеринбург,Свердловская область,Уральский,1544376,56.838207,60.600789
354,Казань,Татарстан,Приволжский,1308660,55.794649,49.111502
651,Нижний Новгород,Нижегородская область,Приволжский,1226076,56.326482,44.005139
1053,Челябинск,Челябинская область,Уральский,1189525,55.159841,61.402555
480,Красноярск,Красноярский край,Сибирский,1187771,56.009117,92.872586
830,Самара,Самарская область,Приволжский,1173299,53.195625,50.101493
1019,Уфа,Башкортостан,Приволжский,1144809,54.726141,55.947499

In [ ]:
#Выгружаем обработанные данные о городах в таблицу базы данных

logger.info("Выгружаем полученные данные о городах в таблицу базы данных")
df_city.to_sql('cities', con=engine, if_exists='replace', index=False)
logger.info("Данные о городах успешно выгружены в таблицу базы данных")

___

## 4. Парсинг данных о погоде через API<a id='soderjanie_4'></a>

In [33]:
# Устанавливаем кэш с бесконечным сроком жизни (-1): создаст файл 'api_cache.sqlite'

requests_cache.install_cache('api_cache', backend='sqlite', expire_after=-1)

In [34]:
# Функция для получения данных о погоде через API сайта open-meteo.com

def weather (weather_cities: List[str],
             headers: dict,
             start_date: str,
             end_date: str) -> pd.DataFrame:

    '''
    Функция для получения данных о погоде через API сайта open-meteo.com.
    Args:
        weather_cities: список городов
        headers: заголовок
        start_date: дата начала периода в формате ISO8601: 0000-00-00
        end_date: дата окончания периода в формате ISO8601: 0000-00-00
    '''
    # Список для хранения данных о показателях
    all_data_weather = []
    
    # Сохраняем адрес, по которому обращаемся для получения данных
    url_weather = 'https://archive-api.open-meteo.com/v1/archive'
    logger.info(f'Парсинг данных о погоде из API сайта open-meteo.com')
     
    for weather_city in weather_cities:
        try:
            params_weather = {
            'latitude': df_city[df_city['city_name']==weather_city]['lat'],
            'longitude': df_city[df_city['city_name']==weather_city]['lon'],
            'start_date': start_date,
            'end_date': end_date,
            'hourly': [
                'temperature_2m', 'relative_humidity_2m', 'dew_point_2m', 'apparent_temperature',
                'pressure_msl', 'surface_pressure', 'precipitation', 'rain', 'snowfall', 'cloud_cover', 
                'cloud_cover_low', 'cloud_cover_mid', 'cloud_cover_high', 'shortwave_radiation', 
                'direct_radiation', 'direct_normal_irradiance', 'diffuse_radiation', 
                'global_tilted_irradiance', 'sunshine_duration', 'wind_speed_10m', 'wind_speed_100m', 
                'wind_direction_10m', 'wind_direction_100m', 'wind_gusts_10m', 'et0_fao_evapotranspiration', 
                'weather_code', 'snow_depth', 'vapour_pressure_deficit', 'soil_temperature_0_to_7cm', 
                'soil_temperature_7_to_28cm', 'soil_temperature_28_to_100cm', 
                'soil_temperature_100_to_255cm','soil_moisture_0_to_7cm', 'soil_moisture_7_to_28cm', 
                'soil_moisture_28_to_100cm', 'soil_moisture_100_to_255cm'
            ],
            'daily': [
                'weather_code', 'temperature_2m_max', 'temperature_2m_min', 'apparent_temperature_max', 
                'apparent_temperature_min', 'precipitation_sum', 'rain_sum', 'snowfall_sum', 
                'precipitation_hours', 'sunrise', 'sunset', 'sunshine_duration', 'daylight_duration', 
                'wind_speed_10m_max', 'wind_gusts_10m_max', 'wind_direction_10m_dominant',
                'shortwave_radiation_sum', 'et0_fao_evapotranspiration'
            ],
            'timezone': 'auto'}
            # Отправляем GET запрос к API 
            response_weather = requests.get(url_weather, params=params_weather, headers=headers, timeout=10)
            
            response_weather.raise_for_status()  # Вызовет ошибку, если статус не 200-299
            logger.info(f'Запрос данных о погоде в городе {weather_city} успешно выполнен. {response_weather.from_cache=}')
             # Обрабатываем возможные ошибки при работе с API
        except requests.exceptions.RequestException as e:
            logger.error(f"Ошибка при запросе к API: {e}")
            raise
        except (KeyError, IndexError, ValueError) as e:
            logger.error(f"Ошибка при обработке данных: {e}")
            raise
        # Десериализуем полученный JSON-ответ. 
        # Парсим ответ от API 
        data_weather = response_weather.json()
        # Добавляем данные в общий список
        all_data_weather.append(data_weather)
            
    if all_data_weather:
        logger.info(f'Парсинг данных о погоде из API сайта open-meteo.com успешно завершен')
            
    return all_data_weather

In [35]:
# Выполняем функцию для сохранения данных о погоде

# Указываем заголовок
headers = {'User-Agent': user_agent}

all_data_weather=weather(cities_selected, headers, '2016-01-01', '2025-12-31')

INFO: Парсинг данных о погоде из API сайта open-meteo.com
INFO: Запрос данных о погоде в городе Казань успешно выполнен. response_weather.from_cache=True
INFO: Запрос данных о погоде в городе Новосибирск успешно выполнен. response_weather.from_cache=True
INFO: Парсинг данных о погоде из API сайта open-meteo.com успешно завершен

___

## 5. Предобработка данных о погоде в выбранных городах и выгрузка в таблицу базы данных <a id='soderjanie_5'></a>

In [36]:
#Сохраняем полученные данные о погоде в датафрейм

df_weather = pd.json_normalize(all_data_weather, sep='_')

In [37]:
# Выводим первые 5 строк датафрейма c погодой

df_weather.head()

,latitude,longitude,generationtime_ms,utc_offset_seconds,timezone,timezone_abbreviation,elevation,hourly_units_time,hourly_units_temperature_2m,hourly_units_relative_humidity_2m,...,daily_precipitation_hours,daily_sunrise,daily_sunset,daily_sunshine_duration,daily_daylight_duration,daily_wind_speed_10m_max,daily_wind_gusts_10m_max,daily_wind_direction_10m_dominant,daily_shortwave_radiation_sum,daily_et0_fao_evapotranspiration
0,55.782074,49.124237,5248.989224,10800,Europe/Moscow,GMT+3,82.0,iso8601,°C,%,...,"[0.0, 0.0, 14.0, 0.0, 4.0, 0.0, 14.0, 5.0, 22....","[2016-01-01T08:13, 2016-01-02T08:12, 2016-01-0...","[2016-01-01T15:20, 2016-01-02T15:21, 2016-01-0...","[19241.01, 1478.63, 0.0, 3582.74, 1657.6, 1779...","[25612.66, 25700.26, 25795.33, 25897.61, 26006...","[16.6, 13.5, 24.1, 26.5, 23.8, 16.3, 18.1, 16....","[29.9, 21.2, 46.1, 45.4, 42.5, 27.4, 33.5, 27....","[50, 35, 65, 128, 143, 113, 150, 151, 127, 139...","[2.47, 1.69, 1.12, 1.86, 1.85, 2.27, 1.35, 1.6...","[0.14, 0.07, 0.18, 0.19, 0.16, 0.12, 0.14, 0.1..."
1,55.079086,82.994020,202.665448,25200,Asia/Novosibirsk,GMT+7,149.0,iso8601,°C,%,...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[2016-01-01T09:53, 2016-01-02T09:53, 2016-01-0...","[2016-01-01T17:08, 2016-01-02T17:10, 2016-01-0...","[17764.07, 19708.06, 19726.37, 20212.0, 19626....","[26133.68, 26216.59, 26306.72, 26403.85, 26507...","[10.7, 14.8, 15.1, 14.1, 20.0, 21.7, 11.4, 11....","[16.6, 24.8, 26.3, 24.5, 37.1, 38.5, 19.4, 20....","[337, 34, 39, 34, 51, 88, 104, 169, 328, 50, 8...","[2.45, 2.83, 2.82, 2.74, 2.86, 2.94, 2.23, 2.0...","[0.06, 0.08, 0.1, 0.1, 0.16, 0.24, 0.12, 0.12,..."

In [ ]:
#Выгружаем полученные данные о погоде в буферную таблицу базы данных

logger.info("Выгружаем полученные данные о погоде в буферную таблицу базы данных")
for i, col in enumerate(df_weather.columns):
    if i==0:
        df_col = df_weather[col]
        df_col.to_sql('bufer_weather', con=engine, if_exists='replace', index=False, chunksize=500, method='multi')
    else:
        df_col= df_weather[[df_weather.columns[0],col]]

        df_col.to_sql('temp_table', con=engine, if_exists='replace', index=False, chunksize=500, method='multi')
        with engine.connect() as conn:
            conn.execute(f"ALTER TABLE bufer_weather ADD COLUMN {col} text")

            conn.execute(f"UPDATE bufer_weather SET {col} =(SELECT {col} FROM temp_table  WHERE bufer_weather.{df_weather.columns[0]} = temp_table.{df_weather.columns[0]})")
            conn.execute("DROP TABLE temp_table")
             
logger.info("Данные о погоде успешно выгружены в буферную таблицу базы данных")

In [38]:
# Сохраняем данные почасовые данные о погоде в датафрейм

df_all_data_weather_hourly = pd.DataFrame()
for item in ['time','temperature_2m', 'relative_humidity_2m', 'dew_point_2m', 'apparent_temperature', 
                    'pressure_msl', 'surface_pressure', 'precipitation', 'rain', 'snowfall', 'cloud_cover', 
                    'cloud_cover_low', 'cloud_cover_mid', 'cloud_cover_high', 'shortwave_radiation', 
                    'direct_radiation', 'direct_normal_irradiance', 'diffuse_radiation', 
                    'global_tilted_irradiance', 'sunshine_duration', 'wind_speed_10m', 'wind_speed_100m', 
                    'wind_direction_10m', 'wind_direction_100m', 'wind_gusts_10m', 'et0_fao_evapotranspiration', 
                    'weather_code', 'snow_depth', 'vapour_pressure_deficit', 'soil_temperature_0_to_7cm', 
                    'soil_temperature_7_to_28cm', 'soil_temperature_28_to_100cm', 
                    'soil_temperature_100_to_255cm','soil_moisture_0_to_7cm', 'soil_moisture_7_to_28cm', 
                    'soil_moisture_28_to_100cm', 'soil_moisture_100_to_255cm']:
    if not df_all_data_weather_hourly.empty:
        df_all_data_weather_hourly[item]=pd.json_normalize(all_data_weather,
        meta=['latitude', 'longitude','generationtime_ms', 'utc_offset_seconds',
              'timezone','timezone_abbreviation','elevation'],
        record_path=['hourly', item],
        record_prefix='item_')['item_0']
    else:
        df_all_data_weather_hourly=pd.json_normalize(all_data_weather,
                          meta=['latitude', 'longitude','generationtime_ms', 'utc_offset_seconds',
                                'timezone','timezone_abbreviation','elevation'],
                          record_path=['hourly', item],
                          record_prefix='item_'
                          )
        df_all_data_weather_hourly.rename(columns={'item_0': item}, inplace=True)

In [39]:
# Сохраняем данные дневные о погоде в датафрейм

df_all_data_weather_daily = pd.DataFrame()
for item in ['time','weather_code', 'temperature_2m_max', 'temperature_2m_min', 'apparent_temperature_max', 
                    'apparent_temperature_min', 'precipitation_sum', 'rain_sum', 'snowfall_sum', 
                    'precipitation_hours', 'sunrise', 'sunset', 'sunshine_duration', 'daylight_duration', 
                    'wind_speed_10m_max', 'wind_gusts_10m_max', 'wind_direction_10m_dominant',
                    'shortwave_radiation_sum', 'et0_fao_evapotranspiration']:
    if not df_all_data_weather_daily.empty:
        df_all_data_weather_daily[item]=pd.json_normalize(all_data_weather,
        meta=['latitude', 'longitude','generationtime_ms', 'utc_offset_seconds',
              'timezone','timezone_abbreviation','elevation'],
        record_path=['daily', item],
        record_prefix='item_')['item_0']
    else:
        df_all_data_weather_daily=pd.json_normalize(all_data_weather,
                          meta=['latitude', 'longitude','generationtime_ms', 'utc_offset_seconds',
                                'timezone','timezone_abbreviation','elevation'],
                          record_path=['daily', item],
                          record_prefix='item_'
                          )
        df_all_data_weather_daily.rename(columns={'item_0': item}, inplace=True)

In [40]:
#Выделяем данные о дате и времени в отдельные колонки в датафрейме с почасовыми данными о погоде

df_all_data_weather_hourly[['date', 'hour']]=df_all_data_weather_hourly['time'].str.split('T', expand=True)

In [41]:
#Оставим только необходимые для анализа колонки в датафрейме с почасовыми данными о погоде

df_all_data_weather_hourly=df_all_data_weather_hourly[['latitude', 'longitude',
                    'timezone_abbreviation', 'date', 'hour','weather_code', 
                    'temperature_2m', 'dew_point_2m', 'precipitation', 'rain', 
                    'snowfall', 'snow_depth', 'sunshine_duration', 'wind_speed_10m', 
                    'wind_direction_10m', 'wind_gusts_10m', 
                     'cloud_cover']]

In [42]:
#Выделяем данные о дате и времени восхода солнца в отдельные колонки в датафрейме с дневными данными о погоде

df_all_data_weather_daily[['sunrise_date', 'sunrise_hour']]=df_all_data_weather_daily['sunrise'].str.split('T', expand=True)

In [43]:
#Выделяем данные о дате и времени захода солнца в отдельные колонки в датафрейме с дневными данными о погоде

df_all_data_weather_daily[['sunset_date', 'sunset_hour']]=df_all_data_weather_daily['sunset'].str.split('T', expand=True)

In [44]:
#Изменяем название колонки в датафрейме с дневными данными о погоде

df_all_data_weather_daily.rename(columns={'time': 'date'}, inplace=True)

In [45]:
#Оставим только необходимые для анализа колонки в датафрейме с дневными данными о погоде

df_all_data_weather_daily=df_all_data_weather_daily[['latitude', 'longitude', 'date',  
                    'sunrise_hour', 'sunset_hour', 
                    'daylight_duration', 'precipitation_sum', 
                    'rain_sum', 'snowfall_sum'
                   ]]

In [46]:
#Объединим датафреймы с почасовыми и дневными данными о погоде

df_all_data_weather_hourly=df_all_data_weather_hourly.merge(df_all_data_weather_daily, on=['latitude', 'longitude', 'date'], how='left')

In [47]:
#Изменяем тип данных полей с координатами на float

df_all_data_weather_hourly['latitude'] = df_all_data_weather_hourly['latitude'].astype('float')
df_all_data_weather_hourly['longitude'] = df_all_data_weather_hourly['longitude'].astype('float')

In [48]:
#Изменяем тип данных с датой

df_all_data_weather_hourly['date'] = pd.to_datetime(df_all_data_weather_hourly['date'])

In [49]:
#Выводим информацию об объединенном датафрейме

df_all_data_weather_hourly.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 175344 entries, 0 to 175343
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   latitude               175344 non-null  float64
 1   longitude              175344 non-null  float64
 2   timezone_abbreviation  175344 non-null  object
 3   date                   175344 non-null  datetime64[ns]
 4   hour                   175344 non-null  object
 5   weather_code           175344 non-null  int64
 6   temperature_2m         175344 non-null  float64
 7   dew_point_2m           175344 non-null  float64
 8   precipitation          175344 non-null  float64
 9   rain                   175344 non-null  float64
 10  snowfall               175344 non-null  float64
 11  snow_depth             175344 non-null  float64
 12  sunshine_duration      175344 non-null  float64
 13  wind_speed_10m         175344 non-null  float64
 14  wind_direction_10m     175344 non-null  int64
 15  wind_gusts_10m         175344 non-null  float64
 16  cloud_cover            175344 non-null  int64
 17  sunrise_hour           175344 non-null  object
 18  sunset_hour            175344 non-null  object
 19  daylight_duration      175344 non-null  float64
 20  precipitation_sum      175344 non-null  float64
 21  rain_sum               175344 non-null  float64
 22  snowfall_sum           175344 non-null  float64
dtypes: datetime64[ns](1), float64(15), int64(3), object(4)
memory usage: 32.1+ MB

In [50]:
#Выводим первые 5 строк объединенного датафрейма

df_all_data_weather_hourly.head()

,latitude,longitude,timezone_abbreviation,date,hour,weather_code,temperature_2m,dew_point_2m,precipitation,rain,...,wind_speed_10m,wind_direction_10m,wind_gusts_10m,cloud_cover,sunrise_hour,sunset_hour,daylight_duration,precipitation_sum,rain_sum,snowfall_sum
0,55.782074,49.124237,GMT+3,2016-01-01,00:00,3,-16.2,-19.1,0.0,0.0,...,15.5,54,28.1,98,08:13,15:20,25612.66,0.0,0.0,0.0
1,55.782074,49.124237,GMT+3,2016-01-01,01:00,3,-16.6,-19.6,0.0,0.0,...,14.7,62,27.7,99,08:13,15:20,25612.66,0.0,0.0,0.0
2,55.782074,49.124237,GMT+3,2016-01-01,02:00,3,-17.0,-20.0,0.0,0.0,...,14.7,62,27.0,84,08:13,15:20,25612.66,0.0,0.0,0.0
3,55.782074,49.124237,GMT+3,2016-01-01,03:00,2,-18.0,-21.0,0.0,0.0,...,15.0,60,27.4,64,08:13,15:20,25612.66,0.0,0.0,0.0
4,55.782074,49.124237,GMT+3,2016-01-01,04:00,1,-18.9,-21.9,0.0,0.0,...,15.2,59,28.4,36,08:13,15:20,25612.66,0.0,0.0,0.0

In [51]:
#Добавим колонку с названием города

df_all_data_weather_hourly['n_p'] = np.where(df_all_data_weather_hourly['longitude']==49.124237, 'Казань', 'Новосибирск')

In [52]:
# Проверяем уникальные значения в категориальных столбцах

for column in ['latitude', 'longitude', 'timezone_abbreviation', 'weather_code', 'n_p']:
    print(f'Уникальные значения в столбце {column}:')
    print(df_all_data_weather_hourly[column].sort_values().unique())
    print()

Уникальные значения в столбце latitude:
[55.079086 55.782074]

Уникальные значения в столбце longitude:
[49.124237 82.99402 ]

Уникальные значения в столбце timezone_abbreviation:
['GMT+3' 'GMT+7']

Уникальные значения в столбце weather_code:
[ 0  1  2  3 51 53 55 61 63 65 71 73 75]

Уникальные значения в столбце n_p:
['Казань' 'Новосибирск']

In [53]:
# Проверяем полные дубликаты в датафрейме

df_all_data_weather_hourly.duplicated().sum()

0

In [ ]:
#Выгружаем обработанные данные о погоде в таблицу базы данных
logger.info("Выгружаем обработанные данные о погоде в таблицу базы данных")
df_all_data_weather_hourly.to_sql('weather', con=engine, if_exists='append', index=False)  
logger.info("Данные о погоде успешно выгружены в таблицу базы данных")

___

## 6. Получение ОКАТО-кодов регионов РФ<a id='soderjanie_6'></a>

In [54]:
#Функция для получения ОКАТО-коды всех регионов РФ (877 - код РФ)
#дата всегда прошлый месяц

'''
Функция для получения ОКАТО-кодов регионов РФ с сайта gibdd.ru.
'''

def get_all_regions(user_agent: str):
    
    #По умолчанию берем самые свежие данные, за месяц перед текущим
    now = datetime.now()
    year = now.year
    month = now.month - 1 if now.month > 1 else 12 
    if month == 12:
        year -= 1
        
    #Получаем список регионов РФ
    logger.info("Получаем список регионов РФ.")  
    rf_payload = {
        "maptype": 1,
        "region": "877", 
        "date": f'["MONTHS:{month}.{year}"]',
        "pok": "1"
    }
    
    #Указываем заголовок
    headers = {
        'User-Agent': user_agent,
        'Content-Type': 'application/json'
    }
    #Отправляем запрос к stat.gibdd.ru
    try:
        response = requests.post(
            "http://stat.gibdd.ru/map/getMainMapData",
            json=rf_payload,
            headers=headers,
            timeout=30
        )
        
        # Проверка ответа
        if response.status_code != 200:
            logger.error(f"Ошибка: {response.status_code}")
            return 
                
        
        result = response.json()
        metabase = json.loads(result["metabase"])
        maps_data = json.loads(metabase[0]["maps"])
        
        #Получаем регионы + ОКТМО
        regions = []
        for region in maps_data:
            regions.append({
                "id": region["id"],
                "name": region["name"],
                "districts": []
            })
        
        logger.info(f"Найдено {len(regions)} регионов")
              
        for i, region in enumerate(regions, 1):
            print(f"[{i}/{len(regions)}] {region['name']} ({region['id']})...")
            
            # Получаем ОКАТО-коды муниципальных образований для всех регионов
            region_payload = {
                "maptype": 1,
                "region": region["id"],
                "date": f'["MONTHS:{month}.{year}"]',
                "pok": "1"
            }
            
            #Отправляем запрос к stat.gibdd.ru
            try:
                reg_response = requests.post(
                    "http://stat.gibdd.ru/map/getMainMapData",
                    json=region_payload,
                    headers=headers,
                    timeout=30
                )
                
                # Проверка ответа
                if reg_response.status_code == 200:
                    reg_result = reg_response.json()
                    reg_metabase = json.loads(reg_result["metabase"])
                    reg_maps_data = json.loads(reg_metabase[0]["maps"])
                    
                    municipalities = []
                    for municipality in reg_maps_data:
                        municipalities.append({
                            "id": municipality["id"],
                            "name": municipality["name"]
                        })
                    
                    region["districts"] = municipalities
                    logger.info(f"найдено {len(municipalities)} муниципалитетов")
                else:
                    logger.error(f"ошибка {reg_response.status_code}")
                    
            except Exception as e:
                logger.error(f"ошибка: {e}")
            
            if i < len(regions):
                time.sleep(0.5)
        
        filename = "regions_all.json"
        with open(filename, "w", encoding="utf-8") as f:
            json.dump(regions, f, ensure_ascii=False, indent=2)
        
        total_municipalities = sum(len(r["districts"]) for r in regions)
        logger.info(f"Файл: {filename}")
        logger.info(f"Регионов: {len(regions)}")
        logger.info(f"Всего муниципалитетов: {total_municipalities}")
                
    except Exception as e:
        logger.error(f"Критическая ошибка: {e}")
        
    return regions

In [55]:
#Выполняем функцию для получения ОКАТО-кодов всех регионов РФ и их сохранения

if __name__ == "__main__": 

    result=get_all_regions(user_agent)

INFO: Получаем список регионов РФ.
INFO: Найдено 90 регионов
INFO: найдено 13 муниципалитетов

[1/90] Ямало-Ненецкий АО (71140)...

INFO: найдено 21 муниципалитетов

[2/90] Ханты-Мансийский АО (71100)...

INFO: найдено 24 муниципалитетов

[3/90] Тюменская область (71)...

INFO: найдено 1 муниципалитетов

[4/90] Ненецкий АО (10011)...

INFO: найдено 6 муниципалитетов

[5/90] Еврейская автономная область (99)...

INFO: найдено 35 муниципалитетов

[6/90] Республика Саха (Якутия) (98)...

INFO: найдено 24 муниципалитетов

[7/90] Чувашская Республика (97)...

INFO: найдено 17 муниципалитетов

[8/90] Чеченская Республика (96)...

INFO: найдено 13 муниципалитетов

[9/90] Республика Хакасия (95)...

INFO: найдено 30 муниципалитетов

[10/90] Удмуртская Республика (94)...

INFO: найдено 19 муниципалитетов

[11/90] Республика Тыва (93)...

INFO: найдено 45 муниципалитетов

[12/90] Республика Татарстан (92)...

INFO: найдено 12 муниципалитетов

[13/90] Карачаево-Черкесская Республика (91)...

INFO: найдено 9 муниципалитетов

[14/90] Республика Северная Осетия - Алания (90)...

INFO: найдено 11 муниципалитетов

[15/90] Республика Алтай (84)...

INFO: найдено 12 муниципалитетов

[16/90] Кабардино-Балкарская Республика (83)...

INFO: найдено 51 муниципалитетов

[17/90] Республика Дагестан (82)...

INFO: найдено 23 муниципалитетов

[18/90] Республика Бурятия (81)...

INFO: найдено 23 муниципалитетов

[19/90] Республика Мордовия (89)...

INFO: найдено 16 муниципалитетов

[20/90] Республика Марий Эл (88)...

INFO: найдено 20 муниципалитетов

[21/90] Республика Коми (87)...

INFO: найдено 18 муниципалитетов

[22/90] Республика Карелия (86)...

INFO: найдено 14 муниципалитетов

[23/90] Республика Калмыкия (85)...

INFO: найдено 63 муниципалитетов

[24/90] Республика Башкортостан (80)...

INFO: найдено 9 муниципалитетов

[25/90] Республика Адыгея (79)...

INFO: найдено 20 муниципалитетов

[26/90] Ярославская область (78)...

INFO: найдено 7 муниципалитетов

[27/90] Чукотский автономный округ (77)...

INFO: найдено 33 муниципалитетов

[28/90] Забайкальский край (76)...

INFO: найдено 42 муниципалитетов

[29/90] Челябинская область (75)...

INFO: найдено 24 муниципалитетов

[30/90] Ульяновская область (73)...

INFO: найдено 24 муниципалитетов

[31/90] Тульская область (70)...

INFO: найдено 20 муниципалитетов

[32/90] Томская область (69)...

INFO: найдено 27 муниципалитетов

[33/90] Тамбовская область (68)...

INFO: найдено 27 муниципалитетов

[34/90] Смоленская область (66)...

INFO: найдено 60 муниципалитетов

[35/90] Свердловская область (65)...

INFO: найдено 18 муниципалитетов

[36/90] Сахалинская область (64)...

INFO: найдено 41 муниципалитетов

[37/90] Саратовская область (63)...

INFO: найдено 26 муниципалитетов

[38/90] Рязанская область (61)...

INFO: найдено 54 муниципалитетов

[39/90] Ростовская область (60)...

INFO: найдено 26 муниципалитетов

[40/90] Псковская область (58)...

INFO: найдено 45 муниципалитетов

[41/90] Пермский край (57)...

INFO: найдено 30 муниципалитетов

[42/90] Пензенская область (56)...

INFO: найдено 25 муниципалитетов

[43/90] Орловская область (54)...

INFO: найдено 43 муниципалитетов

[44/90] Оренбургская область (53)...

INFO: найдено 33 муниципалитетов

[45/90] Омская область (52)...

INFO: найдено 34 муниципалитетов

[46/90] Новосибирская область (50)...

INFO: найдено 22 муниципалитетов

[47/90] Новгородская область (49)...

INFO: найдено 17 муниципалитетов

[48/90] Мурманская область (47)...

INFO: найдено 71 муниципалитетов

[49/90] Московская область (46)...

INFO: найдено 147 муниципалитетов

[50/90] г. Москва (45)...

INFO: найдено 9 муниципалитетов

[51/90] Магаданская область (44)...

INFO: найдено 20 муниципалитетов

[52/90] Липецкая область (42)...

INFO: найдено 18 муниципалитетов

[53/90] Ленинградская область (41)...

INFO: найдено 18 муниципалитетов

[54/90] г. Санкт-Петербург (40)...

INFO: найдено 29 муниципалитетов

[55/90] Курская область (38)...

INFO: найдено 26 муниципалитетов

[56/90] Курганская область (37)...

INFO: найдено 33 муниципалитетов

[57/90] Самарская область (36)...

INFO: найдено 26 муниципалитетов

[58/90] Костромская область (34)...

INFO: найдено 40 муниципалитетов

[59/90] Кировская область (33)...

INFO: найдено 31 муниципалитетов

[60/90] Кемеровская область - Кузбасс (32)...

INFO: найдено 13 муниципалитетов

[61/90] Камчатский край (30)...

INFO: найдено 26 муниципалитетов

[62/90] Калужская область (29)...

INFO: найдено 39 муниципалитетов

[63/90] Тверская область (28)...

INFO: найдено 20 муниципалитетов

[64/90] Калининградская область (27)...

INFO: найдено 7 муниципалитетов

[65/90] Республика Ингушетия (26)...

INFO: найдено 38 муниципалитетов

[66/90] Иркутская область (25)...

INFO: найдено 23 муниципалитетов

[67/90] Ивановская область (24)...

INFO: найдено 52 муниципалитетов

[68/90] Нижегородская область (22)...

INFO: найдено 34 муниципалитетов

[69/90] Воронежская область (20)...

INFO: найдено 28 муниципалитетов

[70/90] Вологодская область (19)...

INFO: найдено 35 муниципалитетов

[71/90] Волгоградская область (18)...

INFO: найдено 21 муниципалитетов

[72/90] Владимирская область (17)...

INFO: найдено 29 муниципалитетов

[73/90] Брянская область (15)...

INFO: найдено 22 муниципалитетов

[74/90] Белгородская область (14)...

INFO: найдено 13 муниципалитетов

[75/90] Астраханская область (12)...

INFO: найдено 26 муниципалитетов

[76/90] Архангельская область (11)...

INFO: найдено 23 муниципалитетов

[77/90] Амурская область (10)...

INFO: найдено 19 муниципалитетов

[78/90] Хабаровский край (8)...

INFO: найдено 33 муниципалитетов

[79/90] Ставропольский край (7)...

INFO: найдено 33 муниципалитетов

[80/90] Приморский край (5)...

INFO: найдено 58 муниципалитетов

[81/90] Красноярский край (4)...

INFO: найдено 44 муниципалитетов

[82/90] Краснодарский край (3)...

INFO: найдено 68 муниципалитетов

[83/90] Алтайский край (1)...

INFO: найдено 22 муниципалитетов

[84/90] Республика Крым (35)...

INFO: найдено 2 муниципалитетов

[85/90] г. Севастополь (67)...

INFO: найдено 1 муниципалитетов

[86/90] Сириус (101)...

INFO: найдено 31 муниципалитетов

[87/90] Луганская Народная Республика (958)...

INFO: найдено 30 муниципалитетов

[88/90] Донецкая Народная Республика (960)...

INFO: найдено 23 муниципалитетов

[89/90] Запорожская область (956)...

INFO: найдено 22 муниципалитетов
INFO: Файл: regions_all.json

[90/90] Херсонская область (957)...

INFO: Регионов: 90
INFO: Всего муниципалитетов: 2530

___

## 7. Предобработка данных о кодах ОКТМО и их выгрузка в таблицу базы данных<a id='soderjanie_7'></a>

In [56]:
#Сохраняем полученные ОКАТО-коды в датафрейм

df_regions_code_bufer=pd.json_normalize(result)

In [57]:
#Выводим первые 5 строк датафрейма с ОКАТО-кодами

df_regions_code_bufer.head()

,id,name,districts
0,71140,Ямало-Ненецкий АО,"[{'id': '71166', 'name': 'Шурышкарский район'}..."
1,71100,Ханты-Мансийский АО,"[{'id': '71126', 'name': 'Сургутский район'}, ..."
2,71,Тюменская область,"[{'id': '712581', 'name': 'Ярковский район'}, ..."
3,10011,Ненецкий АО,"[{'id': '11100', 'name': 'Ненецкий АО'}]"
4,99,Еврейская автономная область,"[{'id': '99205', 'name': 'Биробиджанский район..."

In [58]:
# Преобразуем столбец датафрейма с данными о регионах в JSON-строку

for i, item  in enumerate(df_regions_code_bufer['districts']):
    df_regions_code_bufer['districts'][i]=json.dumps(item)

In [ ]:
#Выгружаем полученные данные о кодах ОКАТО в буферную таблицу базы данных

logger.info("Выгружаем полученные данные о кодах ОКАТО в буферную таблицу базы данных")
df_regions_code_bufer.to_sql('bufer_codes_oktmo', con=engine, if_exists='replace', index=False, chunksize=500, method='multi')
logger.info("Данные о кодах ОКАТО успешно выгружены в буферную таблицу базы данных")

In [59]:
#Сохраняем полученные ОКАТО-коды в датафрейм, нормалтзуя данные с помощью json_normalize

df_regions_code=pd.json_normalize(result,meta=['id', 'name'],
        record_path=['districts'],
        record_prefix='districts_')

In [60]:
#Выводим первые 5 строк датафрейма с ОКАТО-кодами

df_regions_code.head()

  districts_id           districts_name     id               name
0        71166       Шурышкарский район  71140  Ямало-Ненецкий АО
1        71153  Красноселькупский район  71140  Ямало-Ненецкий АО
2        71158       Приуральский район  71140  Ямало-Ненецкий АО
3        71156          Надымский район  71140  Ямало-Ненецкий АО
4        71160          Пуровский район  71140  Ямало-Ненецкий АО

In [61]:
#Выводим информацию о датафрейме

df_regions_code.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2530 entries, 0 to 2529
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   districts_id    2530 non-null   object
 1   districts_name  2530 non-null   object
 2   id              2530 non-null   object
 3   name            2530 non-null   object
dtypes: object(4)
memory usage: 79.2+ KB

In [62]:
# Преобразуем и очистим данные о названии муниципалитета

df_regions_code['districts_name'] = df_regions_code['districts_name'].str.replace('г.', '').str.strip()

/tmp/ipykernel_338/1553382197.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  df_regions_code['districts_name'] = df_regions_code['districts_name'].str.replace('г.', '').str.strip()

In [63]:
# Проверяем уникальные значения в категориальных столбцах

for column in ['id', 'name']:
    print(f'Уникальные значения в столбце {column}:')
    print(df_regions_code[column].sort_values().unique())
    print(f'Число уникальных значения в столбце {column}:')
    print(df_regions_code[column].nunique())
    print()

Уникальные значения в столбце id:
['1' '10' '10011' '101' '11' '12' '14' '15' '17' '18' '19' '20' '22' '24'
 '25' '26' '27' '28' '29' '3' '30' '32' '33' '34' '35' '36' '37' '38' '4'
 '40' '41' '42' '44' '45' '46' '47' '49' '5' '50' '52' '53' '54' '56' '57'
 '58' '60' '61' '63' '64' '65' '66' '67' '68' '69' '7' '70' '71' '71100'
 '71140' '73' '75' '76' '77' '78' '79' '8' '80' '81' '82' '83' '84' '85'
 '86' '87' '88' '89' '90' '91' '92' '93' '94' '95' '956' '957' '958' '96'
 '960' '97' '98' '99']
Число уникальных значения в столбце id:
90

Уникальные значения в столбце name:
['Алтайский край' 'Амурская область' 'Архангельская область'
 'Астраханская область' 'Белгородская область' 'Брянская область'
 'Владимирская область' 'Волгоградская область' 'Вологодская область'
 'Воронежская область' 'Донецкая Народная Республика'
 'Еврейская автономная область' 'Забайкальский край' 'Запорожская область'
 'Ивановская область' 'Иркутская область'
 'Кабардино-Балкарская Республика' 'Калининградская область'
 'Калужская область' 'Камчатский край' 'Карачаево-Черкесская Республика'
 'Кемеровская область - Кузбасс' 'Кировская область' 'Костромская область'
 'Краснодарский край' 'Красноярский край' 'Курганская область'
 'Курская область' 'Ленинградская область' 'Липецкая область'
 'Луганская Народная Республика' 'Магаданская область'
 'Московская область' 'Мурманская область' 'Ненецкий АО'
 'Нижегородская область' 'Новгородская область' 'Новосибирская область'
 'Омская область' 'Оренбургская область' 'Орловская область'
 'Пензенская область' 'Пермский край' 'Приморский край'
 'Псковская область' 'Республика Адыгея' 'Республика Алтай'
 'Республика Башкортостан' 'Республика Бурятия' 'Республика Дагестан'
 'Республика Ингушетия' 'Республика Калмыкия' 'Республика Карелия'
 'Республика Коми' 'Республика Крым' 'Республика Марий Эл'
 'Республика Мордовия' 'Республика Саха (Якутия)'
 'Республика Северная Осетия - Алания' 'Республика Татарстан'
 'Республика Тыва' 'Республика Хакасия' 'Ростовская область'
 'Рязанская область' 'Самарская область' 'Саратовская область'
 'Сахалинская область' 'Свердловская область' 'Сириус'
 'Смоленская область' 'Ставропольский край' 'Тамбовская область'
 'Тверская область' 'Томская область' 'Тульская область'
 'Тюменская область' 'Удмуртская Республика' 'Ульяновская область'
 'Хабаровский край' 'Ханты-Мансийский АО' 'Херсонская область'
 'Челябинская область' 'Чеченская Республика' 'Чувашская Республика'
 'Чукотский автономный округ' 'Ямало-Ненецкий АО' 'Ярославская область'
 'г. Москва' 'г. Санкт-Петербург' 'г. Севастополь']
Число уникальных значения в столбце name:
90

In [ ]:
#Выгружаем полученные данные о кодах ОКТМО в таблицу базы данных

logger.info("Выгружаем полученные данные о кодах ОКТМО в таблицу базы данных")
df_regions_code.to_sql('codes_oktmo', con=engine, if_exists='replace', index=False, chunksize=500, method='multi')
logger.info("Данные о кодах ОКТМО успешно выгружены в таблицу базы данных")

In [64]:
#Для выбранных городов выводим строки датафрейма с кодами ОКАТО, их содержащие

for city in cities_selected:
    print(df_regions_code[df_regions_code['districts_name'].str.contains(city, case=False, na=False)])

    districts_id districts_name  id                  name
242        92401         Казань  92  Республика Татарстан
     districts_id       districts_name  id                   name
1183        50240  Новосибирский район  50  Новосибирская область
1187        50401          Новосибирск  50  Новосибирская область

___


## 8. Парсинг данных о ДТП через API<a id='soderjanie_8'></a>

In [65]:
#Функция для получения полных карточек ДТП

def get_dtp_cards(region_id, district_id, year, month, user_agent, start=1, end=300):
    
    """
    Получение полных карточек ДТП с пагинацией
    region_id: ОКАТО региона
    district_id: ОКАТО муниципалитета
    year: год 
    month: месяц
    headers
    """
    logger.info(f'Получение карточек ДТП для муниципалитета с кодом ОКАТО {district_id} региона с кодом ОКАТО {region_id} за период {month}.{year}')
    url = "http://stat.gibdd.ru/map/getDTPCardData"
    
    payload = {
        "data": {
            "date": [f"MONTHS:{month}.{year}"],
            "ParReg": region_id,
            "order": {"type": "1", "fieldName": "dat"},
            "reg": district_id,
            "ind": "1",
            "st": str(start),
            "en": str(end),
            "fil": {
                "isSummary": False  # Полные данные вместо сводных
            },
            "fieldNames": [
                "dat", "time", "coordinates", "infoDtp", "k_ul", "dor", "ndu",
                "k_ts", "ts_info", "pdop", "pog", "osv", "s_pch", "s_pog",
                "n_p", "n_pg", "obst", "sdor", "t_osv", "t_p", "t_s", "v_p", "v_v"
            ]
        }
    }

    headers = {
        "User-Agent": user_agent,
        "Accept": "application/json",
        "Content-Type": "application/json"
    }

    try:
        # Двойное кодирование JSON требуется API ГИБДД
        request_data = {
            "data": json.dumps(payload["data"], separators=(',', ':'))
        }

        response = requests.post(
            url,
            json=request_data,
            headers=headers,
            timeout=30
        )

        if response.status_code == 200:
            response_data = json.loads(response.text)
            return json.loads(response_data["data"]).get("tab", [])
        else:
            logger.error(f"Ошибка HTTP: {response.status_code}")
            return None

    except Exception as e:
        logger.error(f"Ошибка при запросе данных: {str(e)}")
        return None

In [66]:
#Выполнение функции для получения полных карточек ДТП

#Сохраняем пустой список для добавления в него карточек ДТП
dtp_data=[]
#Сохраняем спиок с данными ОКАТО выбранных регионов и муниципалитетов
cities_codes_regions=[['92', '92401'],['50','50401']]
#Сохраняем год начала и окончания периода
year_start=2016
year_end=2025

#Сохраняем месяц начала и окончания периода (если данные за полные года скачиваем, то заполняем 1 и 12 соответсвенно)
month_start=1
month_end=12

#Для кадого месяца в рассматриваемом периоде скачиваем карточки ДТП по выбранным регионам 
#и добавляем их к общему списку
for region_id, district_id in cities_codes_regions:
    for year in range(year_start, year_end+1, 1):
        for month in range (month_start, month_end+1, 1):
            dtp_data_m = get_dtp_cards(region_id, district_id, year, month, user_agent)
            dtp_data.append(dtp_data_m)

INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 1.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 2.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 3.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 4.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 5.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 6.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 7.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 8.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 9.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 10.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 11.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 12.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 1.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 2.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 3.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 4.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 5.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 6.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 7.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 8.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 9.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 10.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 11.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 12.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 1.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 2.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 3.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 4.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 5.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 6.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 7.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 8.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 9.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 10.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 11.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 12.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 1.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 2.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 3.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 4.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 5.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 6.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 7.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 8.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 9.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 10.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 11.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 12.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 1.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 2.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 3.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 4.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 5.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 6.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 7.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 8.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 9.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 10.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 11.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 12.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 1.2021
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 2.2021
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 3.2021
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 4.2021
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 5.2021
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 6.2021
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 7.2021
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 8.2021
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 9.2021
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 10.2021
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 11.2021
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 12.2021
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 1.2022
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 2.2022
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 3.2022
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 4.2022
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 5.2022
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 6.2022
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 7.2022
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 8.2022
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 9.2022
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 10.2022
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 11.2022
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 12.2022
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 1.2023
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 2.2023
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 3.2023
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 4.2023
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 5.2023
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 6.2023
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 7.2023
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 8.2023
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 9.2023
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 10.2023
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 11.2023
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 12.2023
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 1.2024
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 2.2024
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 3.2024
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 4.2024
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 5.2024
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 6.2024
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 7.2024
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 8.2024
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 9.2024
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 10.2024
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 11.2024
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 12.2024
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 1.2025
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 2.2025
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 3.2025
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 4.2025
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 5.2025
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 6.2025
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 7.2025
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 8.2025
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 9.2025
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 10.2025
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 11.2025
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 92401 региона с кодом ОКАТО 92 за период 12.2025
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 1.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 2.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 3.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 4.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 5.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 6.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 7.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 8.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 9.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 10.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 11.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 12.2016
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 1.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 2.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 3.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 4.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 5.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 6.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 7.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 8.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 9.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 10.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 11.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 12.2017
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 1.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 2.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 3.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 4.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 5.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 6.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 7.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 8.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 9.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 10.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 11.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 12.2018
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 1.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 2.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 3.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 4.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 5.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 6.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 7.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 8.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 9.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 10.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 11.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 12.2019
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 1.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 2.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 3.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 4.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 5.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 6.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 7.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 8.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 9.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 10.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 11.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 12.2020
INFO: Получение карточек ДТП для муниципалитета с кодом ОКАТО 50401 региона с кодом ОКАТО 50 за период 1.2021

___

## 9. Предобработка данных о ДТП и их выгрузка в таблицу базы данных<a id='soderjanie_9'></a>

In [67]:
#Сохраняем полученные данные о ДТП в датафрейм

dtp_data_bufer=pd.DataFrame(dtp_data)

In [68]:
# Преобразуем ячейки датафрейма с данными о ДТП в JSON-строки

for i, col in enumerate(dtp_data_bufer.columns):
    for t, item  in enumerate(dtp_data_bufer[col]):
        dtp_data_bufer[t][col]=json.dumps(item)

In [69]:
# Сохраним список с новыми наименованиями колонок датафрейма

new_col=[]
for i in dtp_data_bufer.columns:
    new_col.append(f'card_{i}')

In [70]:
# Измением наименование колонок датафрейма

dtp_data_bufer=dtp_data_bufer.set_axis(new_col, axis=1)

In [71]:
#Выводим первые 2 строки датафрейма

dtp_data_bufer.head(2)

,card_0,card_1,card_2,card_3,card_4,card_5,card_6,card_7,card_8,card_9,...,card_230,card_231,card_232,card_233,card_234,card_235,card_236,card_237,card_238,card_239
0,"{""KartId"": 191002725, ""rowNum"": 1, ""date"": ""30...","{""KartId"": 191250381, ""rowNum"": 1, ""date"": ""29...","{""KartId"": 191663975, ""rowNum"": 1, ""date"": ""31...","{""KartId"": 193074994, ""rowNum"": 1, ""date"": ""30...","{""KartId"": 193698958, ""rowNum"": 1, ""date"": ""31...","{""KartId"": 194540075, ""rowNum"": 1, ""date"": ""30...","{""KartId"": 195946925, ""rowNum"": 1, ""date"": ""31...","{""KartId"": 198294092, ""rowNum"": 1, ""date"": ""31...","{""KartId"": 200064030, ""rowNum"": 1, ""date"": ""30...","{""KartId"": 201563475, ""rowNum"": 1, ""date"": ""31...",...,"{""KartId"": 224676485, ""rowNum"": 1, ""date"": ""31...","{""KartId"": 224730238, ""rowNum"": 1, ""date"": ""30...","{""KartId"": 224793246, ""rowNum"": 1, ""date"": ""31...","{""KartId"": 224859253, ""rowNum"": 1, ""date"": ""30...","{""KartId"": 224933769, ""rowNum"": 1, ""date"": ""31...","{""KartId"": 225011577, ""rowNum"": 1, ""date"": ""31...","{""KartId"": 225083416, ""rowNum"": 1, ""date"": ""30...","{""KartId"": 225155738, ""rowNum"": 1, ""date"": ""31...","{""KartId"": 225217286, ""rowNum"": 1, ""date"": ""30...","{""KartId"": 225406749, ""rowNum"": 1, ""date"": ""31..."
1,"""{\""KartId\"": 191250381, \""rowNum\"": 1, \""date...","{""KartId"": 191292286, ""rowNum"": 2, ""date"": ""29...","{""KartId"": 191661939, ""rowNum"": 2, ""date"": ""31...","{""KartId"": 193147932, ""rowNum"": 2, ""date"": ""30...","{""KartId"": 193729959, ""rowNum"": 2, ""date"": ""31...","{""KartId"": 194540076, ""rowNum"": 2, ""date"": ""30...","{""KartId"": 195946926, ""rowNum"": 2, ""date"": ""31...","{""KartId"": 198293923, ""rowNum"": 2, ""date"": ""31...","{""KartId"": 199960844, ""rowNum"": 2, ""date"": ""30...","{""KartId"": 201545783, ""rowNum"": 2, ""date"": ""31...",...,"{""KartId"": 224676614, ""rowNum"": 2, ""date"": ""31...","{""KartId"": 224746916, ""rowNum"": 2, ""date"": ""30...","{""KartId"": 224793663, ""rowNum"": 2, ""date"": ""31...","{""KartId"": 224986639, ""rowNum"": 2, ""date"": ""30...","{""KartId"": 224933736, ""rowNum"": 2, ""date"": ""31...","{""KartId"": 225013274, ""rowNum"": 2, ""date"": ""30...","{""KartId"": 225084769, ""rowNum"": 2, ""date"": ""30...","{""KartId"": 225155799, ""rowNum"": 2, ""date"": ""31...","{""KartId"": 225217333, ""rowNum"": 2, ""date"": ""30...","{""KartId"": 225349539, ""rowNum"": 2, ""date"": ""31..."

In [ ]:
#Выгружаем полученные данные о ДТП в буферную таблицу базы данных

logger.info("Выгружаем полученные данные о ДТП в буферную таблицу базы данных")
for i, col in enumerate(dtp_data_bufer.columns):
    if i==0:
        df_col = dtp_data_bufer[col]
        df_col.to_sql('bufer_dtp', con=engine, if_exists='replace', chunksize=500, method='multi')

    else:
        df_col= dtp_data_bufer[col]
        df_col.to_sql('temp_table', con=engine, if_exists='replace',  chunksize=500, method='multi')
        with engine.connect() as conn:
            conn.execute(f"ALTER TABLE bufer_dtp ADD COLUMN {col} text")
            conn.execute(f"UPDATE bufer_dtp SET {col}=(SELECT {col} FROM temp_table  WHERE bufer_dtp.index = temp_table.index)")
            conn.execute("DROP TABLE temp_table")
             
logger.info("Данные о ДТП успешно выгружены в буферную таблицу базы данных")

In [72]:
#Основной DataFrame с данными о ДТП (только верхний уровень)

main_data = []
for i in range(len(dtp_data)):
    for item in dtp_data[i]:
        main_item = {
        'KartId': item['KartId'],
        'rowNum': item['rowNum'],
        'date': item['date'],
        'Time': item['Time'],
        'District': item['District'],
        'DTP_V': item['DTP_V'],
        'POG': item['POG'],
        'RAN': item['RAN'],
        'K_TS': item['K_TS'],
        'K_UCH': item['K_UCH'],
        'emtp_number': item['emtp_number']
    }
        main_data.append(main_item)

main_df = pd.DataFrame(main_data)

In [73]:
#Выводим информацию о датафрейме

main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30608 entries, 0 to 30607
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   KartId       30608 non-null  int64
 1   rowNum       30608 non-null  int64
 2   date         30608 non-null  object
 3   Time         30608 non-null  object
 4   District     30608 non-null  object
 5   DTP_V        30608 non-null  object
 6   POG          30608 non-null  int64
 7   RAN          30608 non-null  int64
 8   K_TS         30608 non-null  int64
 9   K_UCH        30608 non-null  int64
 10  emtp_number  30608 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.6+ MB

In [74]:
#Выводим первые 5 строк датафрейма

main_df.head()

,KartId,rowNum,date,Time,District,DTP_V,POG,RAN,K_TS,K_UCH,emtp_number
0,191002725,1,30.01.2016,16:51,Московский р-н,Наезд на пешехода,0,1,1,2,
1,190997161,2,30.01.2016,11:05,Новосавиновский р-н,Наезд на пешехода,0,1,1,2,
2,190998969,3,30.01.2016,01:10,Авиастроительный р-н,Столкновение,0,1,2,3,
3,190996837,4,30.01.2016,09:10,Приволжский р-н,Столкновение,0,1,3,3,
4,190991145,5,30.01.2016,10:15,Вахитовский р-н,Столкновение,0,1,2,3,

In [75]:
#Приводим заголовки столбцов датафрейма в нижний регистр

main_df.columns = main_df.columns.str.lower()

In [76]:
# Изменим тип данных в столбце с датой

main_df['date'] = pd.to_datetime(main_df['date'])

In [77]:
# Добавим столбец со временем, округленным до часа

main_df['time'] = pd.to_datetime(main_df['time'])
main_df['hour'] = main_df['time'].dt.strftime('%H:00')
main_df['time'] =main_df['time'].dt.strftime('%H:%M')

In [78]:
# Проверяем количество уникальных значений в столбце с номерами карточек ДТП

main_df['kartid'].nunique()

30608

In [79]:
# Проверяем уникальные значения в категориальных столбцах

for column in ['dtp_v', 'pog', 'ran', 'k_ts', 'k_uch', 'emtp_number']:
    print(f'Уникальные значения в столбце {column}:')
    print(main_df[column].sort_values().unique())
    print(f'Число уникальных значения в столбце {column}:')
    print(main_df[column].nunique())
    print()

Уникальные значения в столбце dtp_v:
['Возгорание вследствие технической неисправности движущегося или остановившегося ТС, участвующего в дорожном движении.'
 'Иной вид ДТП' 'Наезд на велосипедиста'
 'Наезд на внезапно возникшее препятствие' 'Наезд на животное'
 'Наезд на лицо, использующее для передвижения СИМ'
 'Наезд на лицо, не являющееся участником дорожного движения, осуществляющее какую-либо другую деятельность'
 'Наезд на лицо, не являющееся участником дорожного движения, осуществляющее несение службы'
 'Наезд на лицо, не являющееся участником дорожного движения, осуществляющее производство работ'
 'Наезд на пешехода' 'Наезд на препятствие' 'Наезд на стоящее ТС'
 'Опрокидывание' 'Отбрасывание предмета' 'Падение груза'
 'Падение пассажира' 'Столкновение' 'Съезд с дороги']
Число уникальных значения в столбце dtp_v:
18

Уникальные значения в столбце pog:
[0 1 2 3 4]
Число уникальных значения в столбце pog:
5

Уникальные значения в столбце ran:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 16 19]
Число уникальных значения в столбце ran:
15

Уникальные значения в столбце k_ts:
[1 2 3 4 5 6 7 8 9]
Число уникальных значения в столбце k_ts:
9

Уникальные значения в столбце k_uch:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 20 28]
Число уникальных значения в столбце k_uch:
16

Уникальные значения в столбце emtp_number:
['' '500000003' '500000004' ... '920076288' '920076305' '920082705']
Число уникальных значения в столбце emtp_number:
15627

In [80]:
# Определяем количество явных дубликатов

main_df.duplicated().sum()

0

In [ ]:
#Выгружаем полученные общие данные о ДТП в таблицу базы данных

logger.info("Выгружаем полученные общие данные о ДТП в таблицу базы данных")
main_df.to_sql('dtp_common', con=engine, if_exists='append', index=False, chunksize=500, method='multi')
logger.info("Общие данные о ДТП успешно выгружены в таблицу базы данных")

___

In [81]:
#DataFrame с общей информацией о ДТП (infoDtp)

info_dtp_list = []
for i in range(len(dtp_data)):
    for item in dtp_data[i]:
        info_row = {
        'KartId': item['KartId'],
        'n_p': item['infoDtp'].get('n_p', ''),
        'street': item['infoDtp'].get('street', ''),
        'house': item['infoDtp'].get('house', ''),
        'dor': item['infoDtp'].get('dor', ''),
        'km': item['infoDtp'].get('km', ''),
        'm': item['infoDtp'].get('m', ''),
        'k_ul': item['infoDtp'].get('k_ul', ''),
        'dor_k': item['infoDtp'].get('dor_k', ''),
        'dor_z': item['infoDtp'].get('dor_z', ''),
        's_pch': item['infoDtp'].get('s_pch', ''),
        'osv': item['infoDtp'].get('osv', ''),
        'change_org_motion': item['infoDtp'].get('change_org_motion', ''),
        's_dtp': item['infoDtp'].get('s_dtp', ''),
        'COORD_W': item['infoDtp'].get('COORD_W', ''),
        'COORD_L': item['infoDtp'].get('COORD_L', ''),
        # Преобразуем списки в строки
        'ndu': ', '.join(item['infoDtp'].get('ndu', [])) if item['infoDtp'].get('ndu') else '',
        'sdor': ', '.join(item['infoDtp'].get('sdor', [])) if item['infoDtp'].get('sdor') else '',
        'factor': ', '.join(item['infoDtp'].get('factor', [])) if item['infoDtp'].get('factor') else '',
        's_pog': ', '.join(item['infoDtp'].get('s_pog', [])) if item['infoDtp'].get('s_pog') else '',
        'OBJ_DTP': ', '.join(item['infoDtp'].get('OBJ_DTP', [])) if item['infoDtp'].get('OBJ_DTP') else ''
    }
        info_dtp_list.append(info_row)

info_dtp_df = pd.DataFrame(info_dtp_list)

In [82]:
#Выводим информацию о датафрейме 

info_dtp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30608 entries, 0 to 30607
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   KartId             30608 non-null  int64
 1   n_p                30608 non-null  object
 2   street             30608 non-null  object
 3   house              30608 non-null  object
 4   dor                30608 non-null  object
 5   km                 30608 non-null  object
 6   m                  30608 non-null  object
 7   k_ul               30608 non-null  object
 8   dor_k              30608 non-null  object
 9   dor_z              30608 non-null  object
 10  s_pch              30608 non-null  object
 11  osv                30608 non-null  object
 12  change_org_motion  30608 non-null  object
 13  s_dtp              30608 non-null  object
 14  COORD_W            30608 non-null  object
 15  COORD_L            30608 non-null  object
 16  ndu                30608 non-null  object
 17  sdor               30608 non-null  object
 18  factor             30608 non-null  object
 19  s_pog              30608 non-null  object
 20  OBJ_DTP            30608 non-null  object
dtypes: int64(1), object(20)
memory usage: 4.9+ MB

In [83]:
#Выводим первые 5 строк датафрейма

info_dtp_df.head()

,KartId,n_p,street,house,dor,km,m,k_ul,dor_k,dor_z,...,osv,change_org_motion,s_dtp,COORD_W,COORD_L,ndu,sdor,factor,s_pog,OBJ_DTP
0,191002725,г Казань,пр-кт Ибрагимова,14,,0,0,Магистральные улицы общегородского значения,,Не указано,...,"В темное время суток, освещение включено",Режим движения не изменялся,820,55.838855,49.087961,Не установлены,Перегон (нет объектов на месте ДТП),Сведения отсутствуют,"Пасмурно, Снегопад",Остановка общественного транспорта
1,190997161,г Казань,ул Чистопольская,33 В,,0,0,Магистральные дороги,,Не указано,...,Светлое время суток,Режим движения не изменялся,820,55.819364,49.122089,Недостатки зимнего содержания,Перегон (нет объектов на месте ДТП),Сведения отсутствуют,Пасмурно,Многоквартирные жилые дома
2,190998969,г Казань,ул Беломорская,Челюскина,,0,0,Магистральные улицы общегородского значения,,Не указано,...,"В темное время суток, освещение включено",Режим движения не изменялся,300,55.865159,49.078945,Недостатки зимнего содержания,"Перегон (нет объектов на месте ДТП), Регулируе...",Сведения отсутствуют,Снегопад,"Регулируемый перекрёсток, Многоквартирные жилы..."
3,190996837,г Казань,ул Рихарда Зорге,82,,0,0,Магистральные улицы общегородского значения,,Не указано,...,Светлое время суток,Режим движения не изменялся,070,55.745793,49.21574,Не установлены,Перегон (нет объектов на месте ДТП),Сведения отсутствуют,Пасмурно,Регулируемый перекрёсток
4,190991145,г Казань,ул Горького,Жуковского,,0,0,Магистральные дороги,,Не указано,...,Светлое время суток,Режим движения не изменялся,420,55.794047,49.129092,Недостатки зимнего содержания,"Перегон (нет объектов на месте ДТП), Регулируе...",Отключение электроснабжения на данном элементе...,Пасмурно,Остановка общественного транспорта

In [84]:
#Приводим заголовки столбцов датафрейма в нижний регистр

info_dtp_df.columns = info_dtp_df.columns.str.lower()

In [85]:
# Проверяем уникальные значения в категориальных столбцах

for column in ['n_p', 'km', 'm', 'k_ul', 'dor_k', 'dor_z', 's_pch', 'osv', 'change_org_motion', 's_dtp',  'ndu', 'sdor', 'factor', 's_pog', 'obj_dtp', 'coord_w', 'coord_l']:
    print(f'Уникальные значения в столбце {column}:')
    print(info_dtp_df[column].sort_values().unique())
    print(f'Число уникальных значения в столбце {column}:')
    print(info_dtp_df[column].nunique())
    print()

Уникальные значения в столбце n_p:
['г Казань' 'г Новосибирск' 'д Самосырово' 'с Константиновка' 'с Чебакса']
Число уникальных значения в столбце n_p:
5

Уникальные значения в столбце km:
['0' '1' '10' '11' '12' '126' '13' '14' '15' '16' '17' '18' '19' '2' '20'
 '29' '3' '30' '4' '5' '6' '7' '777' '778' '779' '780' '781' '782' '783'
 '784' '785' '786' '787' '788' '795' '796' '797' '798' '8' '802' '808' '9'
 '967']
Число уникальных значения в столбце km:
43

Уникальные значения в столбце m:
['0' '10' '100' '130' '137' '150' '158' '165' '200' '210' '217' '225'
 '240' '255' '280' '30' '300' '337' '350' '400' '420' '450' '460' '470'
 '480' '500' '53' '55' '550' '557' '570' '600' '617' '630' '650' '671'
 '700' '710' '736' '738' '750' '800' '810' '820' '834' '840' '845' '875'
 '885' '900' '910' '940' '950' '960' '988']
Число уникальных значения в столбце m:
55

Уникальные значения в столбце k_ul:
['' 'Велосипедные дорожки' 'Иные места' 'Магистральные дороги'
 'Магистральные улицы общегородского значения'
 'Магистральные улицы районного значения' 'Парковые дороги'
 'Пешеходные улицы' 'Проезды'
 'Улицы и дороги местного значения в жилой застройке'
 'Улицы и дороги местного значения научно-производственных промышленных и коммунально-складских районов']
Число уникальных значения в столбце k_ul:
11

Уникальные значения в столбце dor_k:
['' '1' '2' '4' '5' '6' '8']
Число уникальных значения в столбце dor_k:
7

Уникальные значения в столбце dor_z:
['Другие места'
 'Местного значения (дорога местного значения, включая относящиеся к собственности поселений, муниципальных районов, городских округов)'
 'Не указано'
 'Региональная или межмуниципальная (дорога регионального или межмуниципального значения)'
 'Федеральная (дорога федерального значения)']
Число уникальных значения в столбце dor_z:
5

Уникальные значения в столбце s_pch:
['Гололедица' 'Загрязненное' 'Залитое (покрытое) водой' 'Заснеженное'
 'Мокрое' 'Не установлено' 'Обработанное противогололедными материалами'
 'Пыльное' 'Свежеуложенная поверхностная обработка' 'Со снежным накатом'
 'Сухое']
Число уникальных значения в столбце s_pch:
11

Уникальные значения в столбце osv:
['В темное время суток, освещение включено'
 'В темное время суток, освещение не включено'
 'В темное время суток, освещение отсутствует' 'Не установлено'
 'Светлое время суток' 'Сумерки']
Число уникальных значения в столбце osv:
6

Уникальные значения в столбце change_org_motion:
['Движение полностью перекрыто' 'Движение частично перекрыто'
 'Режим движения не изменялся']
Число уникальных значения в столбце change_org_motion:
3

Уникальные значения в столбце s_dtp:
['010' '020' '030' '040' '050' '060' '070' '090' '100' '110' '120' '130'
 '140' '190' '200' '210' '220' '230' '290' '300' '310' '320' '330' '340'
 '390' '400' '410' '420' '430' '440' '490' '500' '590' '600' '610' '620'
 '630' '690' '700' '710' '720' '730' '740' '750' '760' '770' '780' '790'
 '800' '810' '820' '830' '840' '850' '860' '870' '880' '890' '900' '910'
 '920' '930' '940' '950' '960' '970' '980' '990']
Число уникальных значения в столбце s_dtp:
68

Уникальные значения в столбце ndu:
['Дефекты покрытия' 'Дефекты покрытия, Иные недостатки'
 'Дефекты покрытия, Недостатки зимнего содержания'
 'Дефекты покрытия, Недостатки зимнего содержания, Неисправное освещение'
 'Дефекты покрытия, Недостатки зимнего содержания, Неудовлетворительное состояние обочин, Отсутствие, плохая различимость горизонтальной разметки проезжей части'
 'Дефекты покрытия, Недостатки зимнего содержания, Отсутствие дорожных знаков в необходимых местах'
 'Дефекты покрытия, Недостатки зимнего содержания, Отсутствие дорожных знаков в необходимых местах, Отсутствие пешеходных ограждений в необходимых местах'
 'Дефекты покрытия, Недостатки зимнего содержания, Отсутствие освещения, Неправильное применение, плохая видимость дорожных знаков'
 'Дефекты покрытия, Недостатки зимнего содержания, Отсутствие, плохая различимость горизонтальной разметки проезжей части'
 'Дефекты покрытия, Недостатки зимнего содержания, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Иные недостатки'
 'Дефекты покрытия, Недостатки зимнего содержания, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Неисправное освещение'
 'Дефекты покрытия, Недостатки зимнего содержания, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Неправильное применение, плохая видимость дорожных знаков'
 'Дефекты покрытия, Недостатки зимнего содержания, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отклонение верха головки рельса трамвайных (железнодорожных) путей, расположенных в пределах проезжей части, относительно покрытия, более чем на 2,0 см'
 'Дефекты покрытия, Недостатки зимнего содержания, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие дорожных знаков в необходимых местах'
 'Дефекты покрытия, Недостатки зимнего содержания, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие освещения'
 'Дефекты покрытия, Недостатки зимнего содержания, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие пешеходных ограждений в необходимых местах'
 'Дефекты покрытия, Недостатки зимнего содержания, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие элементов обустройства остановочного пункта общественного пассажирского транспорта'
 'Дефекты покрытия, Недостаточное освещение'
 'Дефекты покрытия, Неисправное освещение'
 'Дефекты покрытия, Неисправное освещение, Иные недостатки'
 'Дефекты покрытия, Неисправное освещение, Неправильное применение, плохая видимость дорожных знаков'
 'Дефекты покрытия, Неисправное освещение, Несоответствие люков смотровых колодцев и ливневой канализации предъявляемым требованиям'
 'Дефекты покрытия, Неисправность светофора'
 'Дефекты покрытия, Неправильное применение, плохая видимость дорожных знаков'
 'Дефекты покрытия, Неправильное применение, плохая видимость дорожных знаков, Иные недостатки'
 'Дефекты покрытия, Несоответствие люков смотровых колодцев и ливневой канализации предъявляемым требованиям'
 'Дефекты покрытия, Неудовлетворительное состояние обочин'
 'Дефекты покрытия, Неудовлетворительное состояние обочин, Отсутствие, плохая различимость горизонтальной разметки проезжей части'
 'Дефекты покрытия, Неудовлетворительное состояние обочин, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие дорожных знаков в необходимых местах'
 'Дефекты покрытия, Неудовлетворительное состояние обочин, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие тротуаров (пешеходных дорожек)'
 'Дефекты покрытия, Неудовлетворительное состояние обочин, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие элементов обустройства остановочного пункта общественного пассажирского транспорта'
 'Дефекты покрытия, Неудовлетворительное состояние разделительной полосы, Отсутствие, плохая различимость горизонтальной разметки проезжей части'
 'Дефекты покрытия, Отсутствие дорожных знаков в необходимых местах'
 'Дефекты покрытия, Отсутствие дорожных знаков в необходимых местах, Иные недостатки'
 'Дефекты покрытия, Отсутствие дорожных знаков в необходимых местах, Неправильное применение, плохая видимость дорожных знаков'
 'Дефекты покрытия, Отсутствие дорожных знаков в необходимых местах, Неправильное применение, плохая видимость дорожных знаков, Иные недостатки'
 'Дефекты покрытия, Отсутствие дорожных знаков в необходимых местах, Отсутствие дорожных ограждений в необходимых местах, Неправильное применение, плохая видимость дорожных знаков'
 'Дефекты покрытия, Отсутствие дорожных знаков в необходимых местах, Отсутствие освещения'
 'Дефекты покрытия, Отсутствие дорожных знаков в необходимых местах, Отсутствие пешеходных ограждений в необходимых местах'
 'Дефекты покрытия, Отсутствие дорожных знаков в необходимых местах, Отсутствие пешеходных ограждений в необходимых местах, Неисправное освещение'
 'Дефекты покрытия, Отсутствие дорожных знаков в необходимых местах, Отсутствие пешеходных ограждений в необходимых местах, Неисправность светофора'
 'Дефекты покрытия, Отсутствие дорожных ограждений в необходимых местах'
 'Дефекты покрытия, Отсутствие дорожных ограждений в необходимых местах, Отсутствие пешеходных ограждений в необходимых местах, Неправильное применение, плохая видимость дорожных знаков'
 'Дефекты покрытия, Отсутствие освещения'
 'Дефекты покрытия, Отсутствие пешеходных ограждений в необходимых местах'
 'Дефекты покрытия, Отсутствие пешеходных ограждений в необходимых местах, Неисправное освещение'
 'Дефекты покрытия, Отсутствие пешеходных ограждений в необходимых местах, Неисправное освещение, Несоответствие железнодорожного переезда предъявляемым требованиям'
 'Дефекты покрытия, Отсутствие тротуаров (пешеходных дорожек), Отсутствие дорожных знаков в необходимых местах'
 'Дефекты покрытия, Отсутствие тротуаров (пешеходных дорожек), Отсутствие освещения'
 'Дефекты покрытия, Отсутствие элементов обустройства остановочного пункта общественного пассажирского транспорта, Отсутствие тротуаров (пешеходных дорожек), Отсутствие освещения'
 'Дефекты покрытия, Отсутствие, плохая различимость вертикальной разметки'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Иные недостатки'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Нарушения в размещении наружной рекламы'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Недостаточное освещение'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Недостаточное освещение, Неправильное применение, плохая видимость дорожных знаков'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Неисправное освещение'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Неисправное освещение, Неправильное применение, плохая видимость дорожных знаков'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Неисправность светофора'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Неисправность светофора, Неправильное применение, плохая видимость дорожных знаков'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Неправильное применение, плохая видимость дорожных знаков'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Неправильное применение, плохая видимость дорожных знаков, Иные недостатки'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Неправильное применение, плохая видимость дорожных знаков, Несоответствие люков смотровых колодцев и ливневой канализации предъявляемым требованиям'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Несоответствие люков смотровых колодцев и ливневой канализации предъявляемым требованиям'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отклонение верха головки рельса трамвайных (железнодорожных) путей, расположенных в пределах проезжей части, относительно покрытия, более чем на 2,0 см'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие временных ТСОД в местах проведения работ, Неисправное освещение'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие дорожных знаков в необходимых местах'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие дорожных знаков в необходимых местах, Иные недостатки'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие дорожных знаков в необходимых местах, Недостаточное освещение'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие дорожных знаков в необходимых местах, Неисправное освещение'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие дорожных знаков в необходимых местах, Неисправность светофора'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие дорожных знаков в необходимых местах, Неправильное применение, плохая видимость дорожных знаков'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие дорожных знаков в необходимых местах, Несоответствие люков смотровых колодцев и ливневой канализации предъявляемым требованиям'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие дорожных знаков в необходимых местах, Отсутствие дорожных ограждений в необходимых местах'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие дорожных знаков в необходимых местах, Отсутствие освещения'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие дорожных знаков в необходимых местах, Отсутствие пешеходных ограждений в необходимых местах'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие дорожных знаков в необходимых местах, Плохая видимость светофора'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие дорожных ограждений в необходимых местах'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие освещения'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие освещения, Иные недостатки'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие освещения, Неправильное применение, плохая видимость дорожных знаков'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие освещения, Несоответствие люков смотровых колодцев и ливневой канализации предъявляемым требованиям'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие пешеходных ограждений в необходимых местах'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие пешеходных ограждений в необходимых местах, Иные недостатки'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие пешеходных ограждений в необходимых местах, Неисправность светофора'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие пешеходных ограждений в необходимых местах, Неправильное применение, плохая видимость дорожных знаков'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие тротуаров (пешеходных дорожек)'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие тротуаров (пешеходных дорожек), Неправильное применение, плохая видимость дорожных знаков'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие тротуаров (пешеходных дорожек), Отсутствие дорожных знаков в необходимых местах'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие тротуаров (пешеходных дорожек), Отсутствие освещения'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие элементов обустройства остановочного пункта общественного пассажирского транспорта'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие элементов обустройства остановочного пункта общественного пассажирского транспорта, Неправильное применение, плохая видимость дорожных знаков'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие элементов обустройства остановочного пункта общественного пассажирского транспорта, Отсутствие дорожных знаков в необходимых местах'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие, плохая различимость вертикальной разметки, Неправильное применение, плохая видимость дорожных знаков'
 'Дефекты покрытия, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Плохая видимость световозвращателей, размещенных на дорожных ограждениях'
 'Иные недостатки' 'Нарушения в размещении наружной рекламы'
 'Не установлены' 'Недостатки зимнего содержания'
 'Недостатки зимнего содержания, Иные недостатки'
 'Недостатки зимнего содержания, Недостаточное освещение'
 'Недостатки зимнего содержания, Неисправное освещение'
 'Недостатки зимнего содержания, Неисправное освещение, Неисправность светофора'
 'Недостатки зимнего содержания, Неисправное освещение, Неправильное применение, плохая видимость дорожных знаков'
 'Недостатки зимнего содержания, Неисправное освещение, Плохая видимость световозвращателей, размещенных на дорожных ограждениях'
 'Недостатки зимнего содержания, Неисправность светофора'
 'Недостатки зимнего содержания, Неисправность светофора, Отсутствие пешеходных ограждений в необходимых местах'
 'Недостатки зимнего содержания, Неправильное применение, плохая видимость дорожных знаков'
 'Недостатки зимнего содержания, Неправильное применение, плохая видимость дорожных знаков, Иные недостатки'
 'Недостатки зимнего содержания, Неправильное применение, плохая видимость дорожных знаков, Несоответствие дорожных ограждений предъявляемым требованиям'
 'Недостатки зимнего содержания, Неправильное применение, плохая видимость дорожных знаков, Отсутствие пешеходных ограждений в необходимых местах'
 'Недостатки зимнего содержания, Несоответствие дорожных ограждений предъявляемым требованиям'
 'Недостатки зимнего содержания, Неудовлетворительное состояние обочин'
 'Недостатки зимнего содержания, Неудовлетворительное состояние обочин, Отсутствие, плохая различимость горизонтальной разметки проезжей части, Отсутствие тротуаров (пешеходных дорожек)'
 'Недостатки зимнего содержания, Неудовлетворительное состояние разделительной полосы, Отсутствие, плохая различимость горизонтальной разметки проезжей части'
 'Недостатки зимнего содержания, Отсутствие временных ТСОД в местах проведения работ, Неисправное освещение'
 'Недостатки зимнего содержания, Отсутствие дорожных знаков в необходимых местах'
 'Недостатки зимнего содержания, Отсутствие дорожных знаков в необходимых местах, Иные недостатки'
 'Недостатки зимнего содержания, Отсутствие дорожных знаков в необходимых местах, Недостаточное освещение'
 'Недостатки зимнего содержания, Отсутствие дорожных знаков в необходимых местах, Неисправное освещение'
 'Недостатки зимнего содержания, Отсутствие дорожных знаков в необходимых местах, Неисправное освещение, Неправильное применение, плохая видимость дорожных знаков'
 'Недостатки зимнего содержания, Отсутствие дорожных знаков в необходимых местах, Неисправность светофора'
 'Недостатки зимнего содержания, Отсутствие дорожных знаков в необходимых местах, Неисправность светофора, Неправильное применение, плохая видимость дорожных знаков'
 'Недостатки зимнего содержания, Отсутствие дорожных знаков в необходимых местах, Неправильное применение, плохая видимость дорожных знаков'
 'Недостатки зимнего содержания, Отсутствие дорожных знаков в необходимых местах, Отсутствие дорожных ограждений в необходимых местах'
 'Недостатки зимнего содержания, Отсутствие дорожных знаков в необходимых местах, Отсутствие освещения'
 'Недостатки зимнего содержания, Отсутствие дорожных знаков в необходимых местах, Отсутствие пешеходных ограждений в необходимых местах'

In [86]:
info_dtp_df['n_p'] = info_dtp_df['n_p'].str.replace('г ', '').str.strip()

In [87]:
# Определяем количество явных дубликатов

info_dtp_df.duplicated().sum()

0

In [88]:
# Проверяем количество уникальных значений в столбце с номерами карточек ДТП

info_dtp_df['kartid'].nunique()

30608

In [ ]:
#Выгружаем полученные расширенные данные о ДТП в таблицу базы данных

logger.info("Выгружаем полученные расширенные данные о месте и условиях ДТП в таблицу базы данных")
info_dtp_df.to_sql('dtp_info', con=engine, if_exists='append', index=False, chunksize=500, method='multi')
logger.info("Расширенные данные о месте и условиях данные о ДТП успешно выгружены в таблицу базы данных")

___

In [89]:
#DataFrame с информацией о транспортных средствах

ts_data = []
for i in range(len(dtp_data)):
    for item in dtp_data[i]:
        kart_id = item['KartId']
        if 'ts_info' in item['infoDtp']:
            for ts in item['infoDtp']['ts_info']:
                ts_row = {
                'KartId': kart_id,
                'n_ts': ts.get('n_ts', ''),
                'ts_s': ts.get('ts_s', ''),
                't_ts': ts.get('t_ts', ''),
                'marka_ts': ts.get('marka_ts', ''),
                'm_ts': ts.get('m_ts', ''),
                'color': ts.get('color', ''),
                'r_rul': ts.get('r_rul', ''),
                'g_v': ts.get('g_v', ''),
              
                    'm_pov': ts.get('m_pov', ''),
                't_n': ts.get('t_n', ''),
                'f_sob': ts.get('f_sob', ''),
                'o_pf': ts.get('o_pf', '')
            }
                ts_data.append(ts_row)

ts_df = pd.DataFrame(ts_data)

In [90]:
#Выводим информацию о датафрейме

ts_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49937 entries, 0 to 49936
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   KartId    49937 non-null  int64
 1   n_ts      49937 non-null  object
 2   ts_s      49937 non-null  object
 3   t_ts      49937 non-null  object
 4   marka_ts  49937 non-null  object
 5   m_ts      49937 non-null  object
 6   color     49937 non-null  object
 7   r_rul     49937 non-null  object
 8   g_v       49937 non-null  object
 9   m_pov     49937 non-null  object
 10  t_n       49937 non-null  object
 11  f_sob     49937 non-null  object
 12  o_pf      49937 non-null  object
dtypes: int64(1), object(12)
memory usage: 5.0+ MB

In [91]:
#Выводим первые 5 строк датафрейма

ts_df.head()

,KartId,n_ts,ts_s,t_ts,marka_ts,m_ts,color,r_rul,g_v,m_pov,t_n,f_sob,o_pf
0,191002725,1,Нет,"В-класс (малый) до 3,9 м",ВАЗ,Жигули ВАЗ-2107 модификации,Иные цвета,Задний,2006,Передний левый угол,Технические неисправности отсутствуют,Частная собственность,Физические лица
1,190997161,1,Нет,"В-класс (малый) до 3,9 м",SKODA,Fabia,Белый,Передний,2007,Передний левый угол,Технические неисправности отсутствуют,Частная собственность,Физические лица
2,190998969,1,Нет,"С-класс (малый средний, компактный) до 4,3 м",KIA,Rio,Серый,Передний,2014,"Передний правый бок (передняя дверь пассажира,...",Технические неисправности отсутствуют,Частная собственность,Физические лица
3,190998969,2,Нет,"С-класс (малый средний, компактный) до 4,3 м",ВАЗ,Kalina,Красный,Передний,2007,Передний левый угол,Технические неисправности отсутствуют,Частная собственность,Физические лица
4,190996837,1,Нет,"В-класс (малый) до 3,9 м",AUDI,Q7,Белый,Задний,2013,Передний левый угол,Технические неисправности отсутствуют,Частная собственность,Физические лица

In [92]:
#Приводим заголовки столбцов датафрейма в нижний регистр

ts_df.columns = ts_df.columns.str.lower()

In [93]:
# Проверяем уникальные значения в категориальных столбцах

for column in ['n_ts', 'ts_s', 't_ts', 'marka_ts', 'm_ts', 'color', 'r_rul', 't_n', 'f_sob', 'o_pf']:
    print(f'Уникальные значения в столбце {column}:')
    print(ts_df[column].sort_values().unique())
    print(f'Число уникальных значения в столбце {column}:')
    print(ts_df[column].nunique())
    print()

Уникальные значения в столбце n_ts:
['1' '2' '3' '4' '5' '6' '7' '8' '9']
Число уникальных значения в столбце n_ts:
9

Уникальные значения в столбце ts_s:
['Да' 'Нет' 'Осталось на месте ДТП'
 'Скрылось и установлено в срок до 1 суток'
 'Скрылось и установлено в срок от 1 до 3 суток'
 'Скрылось и установлено в срок от 3 до 10 суток'
 'Скрылось и установлено в срок свыше 10 суток' 'Скрылось с места ДТП'
 'до 1 сут.' 'от 1  до 3 сут.' 'от 3 до 10 сут.' 'свыше 10 сут.']
Число уникальных значения в столбце ts_s:
12

Уникальные значения в столбце t_ts:
['' 'D-класс (средний) до 4,6 м'
 'S-класс (высший, представительский класс) более 4,9 м'
 'А-класс (особо малый) до 3,5 м' 'Автобетоносмесители'
 'Автобусы (без типа)' 'Автогрейдеры'
 'Автокраны и транспортные средства, оснащенные кранами-манипуляторами'
 'Автомобили скорой медицинской помощи' 'Автоцементовозы' 'Автоэвакуаторы'
 'Бортовые' 'Бортовые грузовые автомобили' 'В-класс (малый) до 3,9 м'
 'Велосипед с двигателем внутреннего сгорания'
 'Велосипед с электрическим двигателем' 'Велосипеды'
 'Велосипеды (без двигателя)' 'Грузовые автомобили (без типа)'
 'Е-класс (высший средний, бизнес-класс) до 4,9 м' 'Иные ТС'
 'Иные дорожно-строительные и дорожно-эксплуатационные машины и механизмы'
 'Иные мототранспортные средства' 'Квадрициклы' 'Квадроциклы'
 'Легковые автомобили (без типа)'
 'Медицинские комплексы на шасси транспортных средств'
 'Минивэны и универсалы повышенной вместимости' 'Моноколеса'
 'Мопеды с двигателем внутреннего сгорания более 50 см. куб.'
 'Мопеды с двигателем внутреннего сгорания менее 50 см. куб.'
 'Мопеды с электродвигателем менее 4 кВт' 'Мотовелосипеды' 'Мотороллеры'
 'Мототранспорт (без типа)' 'Мотоциклы' 'Одноэтажные длиной не более 5 м'
 'Одноэтажные длиной от 5 до 8 м' 'Одноэтажные длиной от 8 до 12 м'
 'Одноэтажные, сочлененные длиной более 12 м'
 'Оснащённые специализированным оборудованием  автотранспортные средства для коммунального хозяйства и  содержания дорог'
 'Оснащённые специализированным оборудованием автотранспортные средства аварийно-спасательных служб и полиции'
 'Персональное электрическое средство передвижения малой мощности'
 'Подвижной состав ж/д' 'Пожарные автомобили' 'Полуприцепы прочие'
 'Полуприцепы с бортовой платформой' 'Полуприцепы-самосвалы'
 'Полуприцепы-фургоны' 'Полуприцепы-цистерны'
 'Прицепы к легковым автомобилям'
 'Прицепы общего назначения к грузовым автомобилям' 'Прицепы прочие'
 'Прицепы со специализированными кузовами' 'Прицепы тракторные'
 'Прицепы-самосвалы' 'Прицепы-трейлеры' 'Прицепы-цистерны'
 'Прочая спецтехника' 'Прочие' 'Прочие Типы ТС (без типа)'
 'Прочие грузовые автомобили' 'Прочие легковые автомобили'
 'Прочие одноэтажные' 'Прочие одноярусные' 'Рефрижераторы'
 'С-класс (малый средний, компактный) до 4,3 м' 'Самосвалы'
 'Седельные тягачи' 'Снегоходы'
 'Специализированная снегоуборочная техника'
 'Специализированная техника аварийно-спасательного назначения'
 'Специализированная техника военного назначения' 'Спецтехника (без типа)'
 'Спортивные (гоночные)' 'Тракторы' 'Трамваи'
 'Транспортные средства для перевозки денежной выручки и ценных грузов'
 'Транспортные средства для перевозки детей'
 'Транспортные средства для перевозки нефтепродуктов'
 'Транспортные средства оперативно-служебные для перевозки лиц, находящихся под стражей'
 'Транспортные средства, оснащенные подъемниками с рабочими платформами'
 'Троллейбусы' 'Тягачи' 'Фронтальные погрузчики' 'Фургоны' 'Цистерны'
 'Шасси' 'Школьные автобусы' 'Экскаваторы' 'Электросамокаты'
 'Электроскейтборды']
Число уникальных значения в столбце t_ts:
92

Уникальные значения в столбце marka_ts:
['' 'ABM' 'AC' 'ACURA' 'ADMIRAL' 'ALFA ROMEO' 'ALFER' 'APRILIA' 'AUDI'
 'BAJAJ' 'BAW' 'BEDFORD' 'BEIFAN' 'BEIJING' 'BENELLI' 'BENTLEY' 'BM' 'BMW'
 'BRILLIANCE' 'BSA' 'BUELL' 'BUICK' 'BYD' 'CADILLAC' 'CHANG FENG'
 'CHANG-JIANG' 'CHANGAN' 'CHERY' 'CHEVROLET' 'CHRYSLER' 'CITROEN' 'DACIA'
 'DAEWOO' 'DAF' 'DAIHATSU' 'DAIMLER' 'DERBI' 'DERWAYS' 'DKW' 'DODGE'
 'DONG FENG' 'DONGHAI' 'DUCATI' 'Datsun' 'EXEED' 'FAW' 'FERRARI' 'FIAT'
 'FORD' 'FOTON' 'FREIGHTLINER' 'FUQI' 'GAC' 'GAS GAS' 'GEELY'
 'GOLDEN DRAGON' 'GREAT WALL' 'HAFEI' 'HAIMA' 'HARLEY-DAVIDSON' 'HAVAL'
 'HIGER' 'HINDUSTAN' 'HOLDEN' 'HONDA' 'HONGQI' 'HOWO' 'HUMMER' 'HUSQVARNA'
 'HYUNDAI' 'INFINITI' 'INNOCENTI' 'IRISBUS' 'ISUZU' 'IVECO' 'JAC' 'JAGUAR'
 'JAWA-CZ' 'JEEP' 'JIANGHUAI' 'JIANSHE-YAMAHA' 'KANUNI' 'KAWASAKI'
 'KEEWAY' 'KIA' 'KING LONG' 'KINLON MOTORS' 'KTM' 'KYMCO' 'LAND ROVER'
 'LDV' 'LEXUS' 'LIFAN' 'LINCOLN' 'LIVAN' 'LIXIANG' 'LOTUS' 'MAN' 'MAZDA'
 'MERCEDES' 'MINI' 'MINSK' 'MITSUBISHI' 'MOTO GUZZI' 'MOTOLEVO'
 'MOTOTRANS' 'MTT' 'MZ' 'NEOPLAN' 'NISSAN' 'OMODA' 'OPEL' 'PEUGEOT'
 'PLYMOUTH' 'PONTIAC' 'PORSCHE' 'PROTON' 'RAJDOOT' 'RAVON' 'REGAL RAPTOR'
 'RELIANT' 'RENAULT' 'ROVER' 'ROXON' 'SAAB' 'SCANIA' 'SEAT' 'SETRA'
 'SHAANXI' 'SHACMAN' 'SITRAK' 'SKODA' 'SSANGYONG' 'SUBARU' 'SUZUKI' 'SYM'
 'TERBERG' 'TESLA' 'TONGGONG' 'TOYOTA' 'TRIUMPH' 'TROLL' 'VAUXHALL'
 'VICTORY' 'VOLKSWAGEN' 'VOLVO' 'VOXAN' 'XIN KAI' 'YAMAHA' 'YUTONG'
 'ZOTYE' 'ZX' 'БОГДАН' 'ВАЗ' 'ВИС' 'ГАЗ' 'ЗАЗ' 'ЗИД' 'ЗИЛ' 'ИЖ' 'КАВЗ'
 'КАМАЗ' 'КРАЗ' 'ЛАЗ' 'ЛИАЗ' 'ЛУИДОР' 'МАЗ' 'МАЗ-МАН' 'МОСКВИЧ' 'НефАЗ'
 'ПАЗ' 'Прочие марки ТС' 'Прочие марки автобусов'
 'Прочие марки автокранов' 'Прочие марки грузовых ТС'
 'Прочие марки легковых ТС' 'Прочие марки мотоциклов'
 'Прочие марки седельных тягачей' 'Прочие марки строительной техники'
 'ТАГАЗ (TAGAZ)' 'УАЗ' 'УРАЛ']
Число уникальных значения в столбце marka_ts:
182

Уникальные значения в столбце m_ts:
['' ' 9 - 3' ' Жигули  ВАЗ-2101, 02, 03 и модификации' ... 'УАЗ 469'
 'Юпитер' 'прочие модели Hyundai']
Число уникальных значения в столбце m_ts:
1141

Уникальные значения в столбце color:
['' 'Белый' 'Желтый' 'Зеленый' 'Иные цвета' 'Коричневый' 'Красный'
 'Многоцветный' 'Не заполнено' 'Оранжевый' 'Серый' 'Синий' 'Фиолетовый'
 'Черный']
Число уникальных значения в столбце color:
14

Уникальные значения в столбце r_rul:
['' 'Задний' 'Иное расположение рулевого управления' 'Иной' 'Не заполнено'
 'Передний' 'Полноприводные' 'Полноприводный' 'С задним приводом'
 'С передним приводом']
Число уникальных значения в столбце r_rul:
10

Уникальные значения в столбце t_n:
['Износ рисунка протектора'
 'Износ рисунка протектора | Иные неисправности'
 'Износ рисунка протектора | Коэффициент светопропускания стекол менее нормативного, установлены дополнительные предметы или нанесены покрытия, ограничивающие обзорность с места водителя'
 'Износ рисунка протектора | На одну ось ТС установлены шины различных размеров, конструкций (радиальной, диагональной, камерной, бескамерной), моделей, с различными рисунками протектора. На ТС одновременно установлены ошипованные и неошипованные шины'
 'Износ рисунка протектора | Наличие конструктивных изменений по сравнению с серийным ТС, сведения о которых отсутствуют в регистрационных документах'
 'Износ рисунка протектора | Шины по размеру или допустимой нагрузке не соответствуют модели ТС'
 'Иные неисправности'
 'Иные неисправности | На одну ось ТС установлены шины различных размеров, конструкций (радиальной, диагональной, камерной, бескамерной), моделей, с различными рисунками протектора. На ТС одновременно установлены ошипованные и неошипованные шины'
 'Иные неисправности | Отсутствуют предусмотренные конструкцией ТС ремни безопасности и (или) подголовники сидений'
 'Иные неисправности | Отсутствуют предусмотренные конструкцией транспортного средства ремни безопасности и(или) подголовники сидений'
 'Иные неисправности | Ремни безопасности неработоспособны или имеют видимые надрывы'
 'Иные неисправности | Шины по размеру или допустимой нагрузке не соответствуют модели ТС'
 'Коэффициент светопропускания стекол менее нормативного'
 'Коэффициент светопропускания стекол менее нормативного | Иные неисправности'
 'Коэффициент светопропускания стекол менее нормативного, установлены дополнительные предметы или нанесены покрытия, ограничивающие обзорность с места водителя'
 'Коэффициент светопропускания стекол менее нормативного, установлены дополнительные предметы или нанесены покрытия, ограничивающие обзорность с места водителя | Иные неисправности'
 'Коэффициент светопропускания стекол менее нормативного, установлены дополнительные предметы или нанесены покрытия, ограничивающие обзорность с места водителя | На одну ось ТС установлены шины различных размеров, конструкций (радиальной, диагональной, камерной, бескамерной), моделей, с различными рисунками протектора. На ТС одновременно установлены ошипованные и неошипованные шины'
 'Коэффициент светопропускания стекол менее нормативного, установлены дополнительные предметы или нанесены покрытия, ограничивающие обзорность с места водителя | Неисправность стеклоочистительного оборудования'
 'На одну ось ТС установлены шины различных размеров, конструкций (радиальной, диагональной, камерной, бескамерной), моделей, с различными рисунками протектора. На ТС одновременно установлены ошипованные и неошипованные шины'
 'На одну ось ТС установлены шины различных размеров, конструкций (радиальной, диагональной, камерной, бескамерной), моделей, с различными рисунками протектора. На ТС одновременно установлены ошипованные и неошипованные шины | Иные неисправности'
 'На одну ось ТС установлены шины различных размеров, конструкций (радиальной, диагональной, камерной, бескамерной), моделей, с различными рисунками протектора. На ТС одновременно установлены ошипованные и неошипованные шины | Недостатки технического обслуживания (в т.ч. наличие посторонних предметов, ветоши в агрегатах и пр.)'
 'На одну ось ТС установлены шины различных размеров, конструкций (радиальной, диагональной, камерной, бескамерной), моделей, с различными рисунками протектора. На ТС одновременно установлены ошипованные и неошипованные шины | Отсутствуют предусмотренные конструкцией ТС ремни безопасности и (или) подголовники сидений'
 'На одну ось ТС установлены шины различных размеров, конструкций (радиальной, диагональной, камерной, бескамерной), моделей, с различными рисунками протектора. На ТС одновременно установлены ошипованные и неошипованные шины | Ремни безопасности неработоспособны или имеют видимые надрывы'
 'Наличие конструктивных изменений по сравнению с серийным ТС, сведения о которых отсутствуют в регистрационных документах'
 'Наличие конструктивных изменений по сравнению с серийным ТС, сведения о которых отсутствуют в регистрационных документах | Иные неисправности'
 'Наличие конструктивных изменений по сравнению с серийным ТС, сведения о которых отсутствуют в регистрационных документах | Коэффициент светопропускания стекол менее нормативного'
 'Наличие конструктивных изменений по сравнению с серийным ТС, сведения о которых отсутствуют в регистрационных документах | Коэффициент светопропускания стекол менее нормативного, установлены дополнительные предметы или нанесены покрытия, ограничивающие обзорность с места водителя'
 'Наличие конструктивных изменений по сравнению с серийным ТС, сведения о которых отсутствуют в регистрационных документах | На одну ось ТС установлены шины различных размеров, конструкций (радиальной, диагональной, камерной, бескамерной), моделей, с различными рисунками протектора. На ТС одновременно установлены ошипованные и неошипованные шины'
 'Наличие конструктивных изменений по сравнению с серийным ТС, сведения о которых отсутствуют в регистрационных документах | Недостатки технического обслуживания (в т.ч. наличие посторонних предметов, ветоши в агрегатах и пр.)'
 'Наличие конструктивных изменений по сравнению с серийным ТС, сведения о которых отсутствуют в регистрационных документах | Отсутствуют предусмотренные конструкцией ТС ремни безопасности и (или) подголовники сидений'
 'Наличие конструктивных изменений по сравнению с серийным ТС, сведения о которых отсутствуют в регистрационных документах | Технические параметры, указанные на наружной поверхности газовых баллонов автомобилей и автобусов, оснащённых газовой системой питания, не соответствуют данным технического паспорта. Отсутствуют даты последнего и планируемого освидетельствования.'
 'Наличие конструктивных изменений по сравнению с серийным ТС, сведения о которых отсутствуют в регистрационных документах | Шины имеют внешние повреждения (пробои, порезы, разрывы), обнажающие корд'
 'Не устанавливались'
 'Недостатки техобслуживания (в т.ч. наличие посторонних предметов, ветоши в агрегатах и пр.)'
 'Неисправность (нарушение герметичности) топливного бака (газового баллона)'
 'Неисправность внешних световых приборов'
 'Неисправность внешних световых приборов | Износ рисунка протектора'
 'Неисправность внешних световых приборов | Иные неисправности'
 'Неисправность внешних световых приборов | Коэффициент светопропускания стекол менее нормативного, установлены дополнительные предметы или нанесены покрытия, ограничивающие обзорность с места водителя'
 'Неисправность внешних световых приборов | На одну ось ТС установлены шины различных размеров, конструкций (радиальной, диагональной, камерной, бескамерной), моделей, с различными рисунками протектора. На ТС одновременно установлены ошипованные и неошипованные шины'
 'Неисправность внешних световых приборов | Наличие конструктивных изменений по сравнению с серийным ТС, сведения о которых отсутствуют в регистрационных документах'
 'Неисправность внешних световых приборов | Отсутствуют предусмотренные конструкцией ТС ремни безопасности и (или) подголовники сидений'
 'Неисправность внешних световых приборов | Отсутствуют предусмотренные конструкцией транспортного средства ремни безопасности и(или) подголовники сидений'
 'Неисправность внешних световых приборов | Разрыв колеса'
 'Неисправность внешних световых приборов | Шины имеют внешние повреждения (пробои, порезы, разрывы), обнажающие корд'
 'Неисправность внешних световых приборов | Шины не соответствуют модели ТС'
 'Неисправность внешних световых приборов | Шины по размеру или допустимой нагрузке не соответствуют модели ТС'
 'Неисправность рабочей тормозной системы'
 'Неисправность рабочей тормозной системы | Наличие конструктивных изменений по сравнению с серийным ТС, сведения о которых отсутствуют в регистрационных документах'
 'Неисправность рабочей тормозной системы | Неисправность внешних световых приборов'
 'Неисправность рабочей тормозной системы | Неисправность рулевого управления'
 'Неисправность рабочей тормозной системы | Шины по размеру или допустимой нагрузке не соответствуют модели ТС'
 'Неисправность рулевого управления'
 'Неисправность рулевого управления | Износ рисунка протектора'
 'Неисправность рулевого управления | На одну ось ТС установлены шины различных размеров, конструкций (радиальной, диагональной, камерной, бескамерной), моделей, с различными рисунками протектора. На ТС одновременно установлены ошипованные и неошипованные шины'
 'Неисправность рулевого управления | Наличие конструктивных изменений по сравнению с серийным ТС, сведения о которых отсутствуют в регистрационных документах'
 'Неисправность рулевого управления | Неисправность внешних световых приборов'
 'Неисправность рулевого управления | Неисправность тягово-сцепного и(или) опорно-сцепного устройства тягача и(или) прицепного звена'
 'Неисправность рулевого управления | Шины по размеру или допустимой нагрузке не соответствуют модели ТС'
 'Неисправность стеклоочистительного оборудования'
 'Неисправность электрооборудования (электропроводки)'
 'Отсоединение колеса'
 'Отсоединение колеса | Наличие конструктивных изменений по сравнению с серийным ТС, сведения о которых отсутствуют в регистрационных документах'
 'Отсоединение колеса | Неисправность внешних световых приборов'
 'Отсутствуют предусмотренные конструкцией ТС ремни безопасности и (или) подголовники сидений'
 'Отсутствуют предусмотренные конструкцией ТС ремни безопасности и (или) подголовники сидений | Иные неисправности'
 'Отсутствуют предусмотренные конструкцией ТС ремни безопасности и (или) подголовники сидений | Ремни безопасности неработоспособны или имеют видимые надрывы'
 'Отсутствуют предусмотренные конструкцией транспортного средства ремни безопасности и(или) подголовники сидений'
 'Разрыв колеса'
 'Ремни безопасности неработоспособны или имеют видимые надрывы'
 'Ремни безопасности неработоспособны или имеют видимые надрывы | Иные неисправности'
 'Технические неисправности отсутствуют'
 'Технические параметры, указанные на наружной поверхности газовых баллонов автомобилей и автобусов, оснащённых газовой системой питания, не соответствуют данным технического паспорта. Отсутствуют даты последнего и планируемого освидетельствования'
 'Технические параметры, указанные на наружной поверхности газовых баллонов автомобилей и автобусов, оснащённых газовой системой питания, не соответствуют данным технического паспорта. Отсутствуют даты последнего и планируемого освидетельствования | Неисправность топливной системы'
 'Шины имеют внешние повреждения (пробои, порезы, разрывы), обнажающие корд'
 'Шины имеют внешние повреждения (пробои, порезы, разрывы), обнажающие корд | Иные неисправности'
 'Шины не соответствуют модели ТС'
 'Шины не соответствуют модели ТС | Иные неисправности'
 'Шины не соответствуют модели ТС | На одну ось ТС установлены шины различных размеров, конструкций (радиальной, диагональной, камерной, бескамерной), моделей, с различными рисунками протектора. На ТС одновременно установлены ошипованные и неошипованные шины'
 'Шины не соответствуют модели ТС | Неудовлетворительное состояние светоотражающих элементов'
 'Шины не соответствуют модели ТС | Ремни безопасности неработоспособны или имеют видимые надрывы'
 'Шины по размеру или допустимой нагрузке не соответствуют модели ТС'
 'Шины по размеру или допустимой нагрузке не соответствуют модели ТС | Иные неисправности'
 'Шины по размеру или допустимой нагрузке не соответствуют модели ТС | Коэффициент светопропускания стекол менее нормативного, установлены дополнительные предметы или нанесены покрытия, ограничивающие обзорность с места водителя'
 'Шины по размеру или допустимой нагрузке не соответствуют модели ТС | На одну ось ТС установлены шины различных размеров, конструкций (радиальной, диагональной, камерной, бескамерной), моделей, с различными рисунками протектора. На ТС одновременно установлены ошипованные и неошипованные шины'
 'Шины по размеру или допустимой нагрузке не соответствуют модели ТС | Наличие конструктивных изменений по сравнению с серийным ТС, сведения о которых отсутствуют в регистрационных документах'
 'Шины по размеру или допустимой нагрузке не соответствуют модели ТС | Неисправность электрооборудования (электропроводки)'
 'Шины по размеру или допустимой нагрузке не соответствуют модели ТС | Неудовлетворительное состояние светоотражающих элементов'
 'Шины по размеру или допустимой нагрузке не соответствуют модели ТС | Отсутствуют предусмотренные конструкцией ТС ремни безопасности и (или) подголовники сидений'
 'Шины по размеру или допустимой нагрузке не соответствуют модели ТС | Ремни безопасности неработоспособны или имеют видимые надрывы']
Число уникальных значения в столбце t_n:
90

Уникальные значения в столбце f_sob:
['' 'Cобственность иностранных граждан и лиц без гражданства'
 'Cобственность иностранных юридических лиц' 'Иное'
 'Коллективная собственность (общественных объединений, организаций, товариществ и др.)'
 'Муниципальная собственность' 'Смешанная российская собственность'
 'Собственность международных организаций'
 'Собственность субъектов Российской Федерации'
 'Совместная российская и иностранная собственность'
 'Федеральная собственность' 'Частная собственность']
Число уникальных значения в столбце f_sob:
12

Уникальные значения в столбце o_pf:
['' 'Индивидуальные предприниматели без образования юридического лица'
 'Иные неюридические лица' 'Крестьянские (фермерские) хозяйства'
 'Прочие некоммерческие организации' 'Физические лица'
 'Хозяйствующие субъекты без прав юридического лица'
 'Юридические лица, являющиеся коммерческими организациями'
 'Юридические лица, являющиеся некоммерческими организациями']
Число уникальных значения в столбце o_pf:
9

In [94]:
# Определяем количество явных дубликатов

ts_df.duplicated().sum()

0

In [95]:
# Проверяем количество уникальных значений в столбце с номерами карточек ДТП

ts_df['kartid'].nunique()

30608

In [ ]:
#Выгружаем полученные данные о транспортных средствах ДТП в таблицу базы данных

logger.info("Выгружаем полученные данные о транспортных средствах ДТП в таблицу базы данных")
ts_df.to_sql('dtp_transp_sr', con=engine, if_exists='append', index=False, chunksize=500, method='multi')
logger.info("Данные о транспортных средствах ДТП успешно выгружены в таблицу базы данных")

____

In [96]:
#DataFrame с участниками ДТП (из ts_uch)

uch_data = []
for i in range(len(dtp_data)):
    for item in dtp_data[i]:
        kart_id = item['KartId']
        if 'ts_info' in item['infoDtp']:
            for ts in item['infoDtp']['ts_info']:
                n_ts = ts.get('n_ts', '')
                if 'ts_uch' in ts and ts['ts_uch']:
                    for uch in ts['ts_uch']:
                        uch_row = {
                        'KartId': kart_id,
                        'n_ts': n_ts,
                        'K_UCH': uch.get('K_UCH', ''),
                        'S_T': uch.get('S_T', ''),
                        'POL': uch.get('POL', ''),
                        'V_ST': uch.get('V_ST', ''),
                        'ALCO': uch.get('ALCO', ''),
                        'SAFETY_BELT': uch.get('SAFETY_BELT', ''),
                        'S_SM': uch.get('S_SM', ''),
                        'N_UCH': uch.get('N_UCH', ''),
                        'S_SEAT_GROUP': uch.get('S_SEAT_GROUP', ''),
                        'INJURED_CARD_ID': uch.get('INJURED_CARD_ID', ''),
                        # Преобразуем списки нарушений в строки
                        'NPDD': ', '.join(uch.get('NPDD', [])) if uch.get('NPDD') else '',
                        'SOP_NPDD': ', '.join(uch.get('SOP_NPDD', [])) if uch.get('SOP_NPDD') else ''
                    }
                        uch_data.append(uch_row)

uch_data_df = pd.DataFrame(uch_data)

In [97]:
#Выводим информацию о датафрейме

uch_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61282 entries, 0 to 61281
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   KartId           61282 non-null  int64
 1   n_ts             61282 non-null  object
 2   K_UCH            61282 non-null  object
 3   S_T              61282 non-null  object
 4   POL              61282 non-null  object
 5   V_ST             61282 non-null  object
 6   ALCO             61282 non-null  object
 7   SAFETY_BELT      61282 non-null  object
 8   S_SM             61282 non-null  object
 9   N_UCH            61282 non-null  object
 10  S_SEAT_GROUP     61282 non-null  object
 11  INJURED_CARD_ID  61282 non-null  object
 12  NPDD             61282 non-null  object
 13  SOP_NPDD         61282 non-null  object
dtypes: int64(1), object(13)
memory usage: 6.5+ MB

In [98]:
#Выводим первые 5 строк датафрейма

uch_data_df.head()

,KartId,n_ts,K_UCH,S_T,POL,V_ST,ALCO,SAFETY_BELT,S_SM,N_UCH,S_SEAT_GROUP,INJURED_CARD_ID,NPDD,SOP_NPDD
0,191002725,1,Водитель,Не пострадал,Мужской,1,,Да,Нет (не скрывался),1,,,Нет нарушений,Нет нарушений
1,190997161,1,Водитель,Не пострадал,Мужской,20,,Да,Нет (не скрывался),2,,,Нет нарушений,Нет нарушений
2,190998969,1,Водитель,Не пострадал,Мужской,5,,Да,Нет (не скрывался),1,,,Несоблюдение очередности проезда,Нет нарушений
3,190998969,1,Пассажир,"Раненый, находящийся (находившийся) на амбула...",Женский,,,Да,Нет (не скрывался),3,,,Нет нарушений,Нет нарушений
4,190998969,2,Водитель,Не пострадал,Мужской,2,,Да,Нет (не скрывался),2,,,Нет нарушений,Нет нарушений

In [99]:
#Приводим заголовки столбцов датафрейма в нижний регистр 

uch_data_df.columns = uch_data_df.columns.str.lower()

In [100]:
# Проверяем уникальные значения в категориальных столбцах

for column in ['n_ts', 'k_uch', 's_t', 'pol', 'v_st', 'alco', 'safety_belt', 's_sm', 'n_uch', 's_seat_group', 'injured_card_id', 'npdd','sop_npdd']:
    print(f'Уникальные значения в столбце {column}:')
    print(uch_data_df[column].sort_values().unique())
    print(f'Число уникальных значения в столбце {column}:')
    print(uch_data_df[column].nunique())
    print()

Уникальные значения в столбце n_ts:
['1' '2' '3' '4' '5' '6' '7' '8' '9']
Число уникальных значения в столбце n_ts:
9

Уникальные значения в столбце k_uch:
['Велосипедист' 'Велосипедист (не применяется)' 'Водитель' 'Пассажир'
 'Пешеход']
Число уникальных значения в столбце k_uch:
5

Уникальные значения в столбце s_t:
['' 'Не пострадал'
 'Получил телесные повреждения с показанием к лечению в медицинских организациях (кроме разовой медицинской помощи)'
 'Получил телесные повреждения с показанием к лечению в медицинских организациях, фактически лечение не проходил, к категории раненый не относится'
 'Получил травмы с оказанием разовой медицинской помощи, к категории раненый не относится'
 'Раненый, находящийся (находившийся)  на амбулаторном лечении, либо которому по характеру полученных травм обозначена необходимость амбулаторного лечения (вне зависимости от его фактического прохождения)'
 'Раненый, находящийся (находившийся) на амбулаторном лечении, либо в условиях дневного стационара'
 'Раненый, находящийся (находившийся) на стационарном лечении'
 'Скончался в течение 1 суток' 'Скончался в течение 10 суток'
 'Скончался в течение 11 суток' 'Скончался в течение 12 суток'
 'Скончался в течение 14 суток' 'Скончался в течение 15 суток'
 'Скончался в течение 16 суток' 'Скончался в течение 17 суток'
 'Скончался в течение 19 суток' 'Скончался в течение 2 суток'
 'Скончался в течение 20 суток' 'Скончался в течение 22 суток'
 'Скончался в течение 23 суток' 'Скончался в течение 24 суток'
 'Скончался в течение 26 суток' 'Скончался в течение 27 суток'
 'Скончался в течение 28 суток' 'Скончался в течение 3 суток'
 'Скончался в течение 4 суток' 'Скончался в течение 5 суток'
 'Скончался в течение 6 суток' 'Скончался в течение 7 суток'
 'Скончался в течение 8 суток' 'Скончался в течение 9 суток'
 'Скончался на месте ДТП до приезда скорой медицинской помощи'
 'Скончался на месте ДТП по прибытию скорой медицинской помощи, но до транспортировки в мед. организацию'
 'Скончался на месте ДТП по прибытию скорой медицинской помощи, но до транспортировки в медицинское учреждение'
 'Скончался при транспортировке']
Число уникальных значения в столбце s_t:
36

Уникальные значения в столбце pol:
['Женский' 'Мужской' 'Не определен']
Число уникальных значения в столбце pol:
3

Уникальные значения в столбце v_st:
['' '0' '1' '10' '11' '12' '13' '14' '15' '16' '17' '18' '19' '2' '20'
 '21' '22' '23' '24' '25' '26' '27' '28' '29' '3' '30' '31' '32' '33' '34'
 '35' '36' '37' '38' '39' '4' '40' '41' '42' '43' '44' '45' '46' '47' '48'
 '49' '5' '50' '51' '52' '53' '54' '55' '56' '57' '58' '59' '6' '60' '61'
 '62' '64' '66' '7' '8' '9' '95' '96' '99']
Число уникальных значения в столбце v_st:
69

Уникальные значения в столбце alco:
['' '00' '01' '02' '03' '04' '05' '06' '07' '08' '09' '10' '11' '12' '13'
 '14' '15' '16' '17' '18' '19' '20' '21' '22' '23' '24' '25' '26' '27'
 '28' '29' '30' '31' '32' '33' '34' '36' '37' '38' '39' '40' '41' '42'
 '44' '46' '47' '49' '50' '51' '53' '54' '56' '58' '59' '60' '64' '70'
 '76' '88' '99']
Число уникальных значения в столбце alco:
60

Уникальные значения в столбце safety_belt:
['Да' 'Нет']
Число уникальных значения в столбце safety_belt:
2

Уникальные значения в столбце s_sm:
['Не установлен' 'Нет (не скрывался)'
 'Скрылся и впоследствии не установлен'
 'Скрылся, впоследствии разыскан (установлен)']
Число уникальных значения в столбце s_sm:
4

Уникальные значения в столбце n_uch:
['1' '10' '11' '12' '13' '14' '15' '16' '17' '18' '19' '2' '20' '21' '22'
 '23' '24' '25' '26' '27' '28' '3' '4' '5' '6' '7' '8' '9']
Число уникальных значения в столбце n_uch:
28

Уникальные значения в столбце s_seat_group:
['' 'Автокресло' 'Бустер' 'Диагональный РБ' 'Люлька' 'Накладка'
 'Поясной РБ']
Число уникальных значения в столбце s_seat_group:
7

Уникальные значения в столбце injured_card_id:
['']
Число уникальных значения в столбце injured_card_id:
1

Уникальные значения в столбце npdd:
['Выезд на полосу встречного движения'
 'Выезд на полосу встречного движения в местах, где это запрещено'
 'Выезд на полосу встречного движения в местах, где это запрещено, Нарушение требований сигналов светофора'
 'Выезд на полосу встречного движения с разворотом, поворотом налево или объездом препятствия'
 'Выезд на полосу встречного движения с разворотом, поворотом налево или объездом препятствия, Нарушение требований линий разметки'
 'Выезд на полосу встречного движения с разворотом, поворотом налево или объездом препятствия, Нарушение требований линий разметки, Невыполнение требований обеспечения безопасности при начале движения'
 'Выезд на полосу встречного движения с разворотом, поворотом налево или объездом препятствия, Несоблюдение очередности проезда'
 'Выезд на полосу встречного движения с разворотом, поворотом налево или объездом препятствия, Превышение установленной скорости движения'
 'Выезд на полосу встречного движения, Нарушение правил обгона'
 'Выезд на полосу встречного движения, Нарушение правил проезда пешеходного перехода'
 'Выезд на полосу встречного движения, Нарушение правил расположения ТС на проезжей части'
 'Выезд на полосу встречного движения, Нарушение требований сигналов светофора'
 'Выезд на полосу встречного движения, Несоблюдение бокового интервала'
 'Выезд на полосу встречного движения, Несоответствие скорости конкретным условиям движения'
 'Выезд на трамвайные пути встречного направления'
 'Движение вдоль проезжей части при наличии и удовлетворительном состоянии тротуара'
 'Движение во встречном направлении по дороге с односторонним движением'
 'Другие нарушения ПДД водителем'
 'Другие нарушения ПДД водителями (не применяется с 12.2020)'
 'Другие нарушения ПДД водителями (не применяется с 12.2020), Несоблюдение бокового интервала'
 'Иные нарушения' 'Нарушение правил буксировки'
 'Нарушение правил выезда на встречную полосу в местах, где это разрешено'
 'Нарушение правил выезда на встречную полосу в местах, где это разрешено, Нарушение правил обгона'
 'Нарушение правил выезда на встречную полосу в местах, где это разрешено, Неправильный выбор дистанции'
 'Нарушение правил выезда на встречную полосу в местах, где это разрешено, Несоблюдение бокового интервала'
 'Нарушение правил обгона'
 'Нарушение правил обгона, Выезд на полосу встречного движения'
 'Нарушение правил обгона, Выезд на полосу встречного движения в местах, где это запрещено'
 'Нарушение правил обгона, Несоблюдение бокового интервала'
 'Нарушение правил остановки и стоянки'
 'Нарушение правил остановки и стоянки, Другие нарушения ПДД водителем'
 'Нарушение правил перевозки людей' 'Нарушение правил перестроения'
 'Нарушение правил перестроения, Выезд на полосу встречного движения в местах, где это запрещено'
 'Нарушение правил перестроения, Нарушение требований дорожных знаков'
 'Нарушение правил перестроения, Нарушение требований линий разметки'
 'Нарушение правил перестроения, Неподача или неправильная подача сигналов поворота'
 'Нарушение правил перестроения, Несоблюдение бокового интервала'
 'Нарушение правил перестроения, Несоответствие скорости конкретным условиям движения'
 'Нарушение правил перестроения, Превышение установленной скорости движения'
 'Нарушение правил погрузки, выгрузки и крепления грузов'
 'Нарушение правил пользования внешними световыми приборами'
 'Нарушение правил пользования общественным транспортом'
 'Нарушение правил при круговом движении'
 'Нарушение правил проезда ж/д переездов'
 'Нарушение правил проезда остановок трамвая'
 'Нарушение правил проезда пешеходного перехода'
 'Нарушение правил проезда пешеходного перехода, Выезд на полосу встречного движения'
 'Нарушение правил проезда пешеходного перехода, Выезд на полосу встречного движения, Нарушение требований сигналов светофора'
 'Нарушение правил проезда пешеходного перехода, Нарушение требований сигналов светофора'
 'Нарушение правил проезда пешеходного перехода, Непредоставление преимущества в движении пешеходу'
 'Нарушение правил проезда пешеходного перехода, Несоблюдение условий, разрешающих движение транспорта задним ходом'
 'Нарушение правил проезда пешеходного перехода, Несоответствие скорости конкретным условиям движения'
 'Нарушение правил проезда пешеходного перехода, Превышение установленной скорости движения'
 'Нарушение правил расположения ТС на проезжей части'
 'Нарушение правил расположения ТС на проезжей части, Выезд на полосу встречного движения в местах, где это запрещено'
 'Нарушение правил расположения ТС на проезжей части, Нарушение требований сигналов светофора'
 'Нарушение правил расположения ТС на проезжей части, Непредоставление преимущества в движении пешеходу'
 'Нарушение правил расположения ТС на проезжей части, Несоблюдение бокового интервала'
 'Нарушение правил расположения ТС на проезжей части, Несоответствие скорости конкретным условиям движения'
 'Нарушение правил расположения ТС на проезжей части, Превышение установленной скорости движения'
 'Нарушение требований дорожных знаков'
 'Нарушение требований дорожных знаков, Несоблюдение бокового интервала'
 'Нарушение требований дорожных знаков, Несоответствие скорости конкретным условиям движения'
 'Нарушение требований линий разметки'
 'Нарушение требований линий разметки, Выезд на полосу встречного движения'
 'Нарушение требований линий разметки, Выезд на полосу встречного движения с разворотом, поворотом налево или объездом препятствия'
 'Нарушение требований линий разметки, Нарушение правил проезда остановок трамвая, Нарушение требований дорожных знаков'
 'Нарушение требований линий разметки, Нарушение требований дорожных знаков'
 'Нарушение требований линий разметки, Нарушение требований сигналов светофора'
 'Нарушение требований сигналов регулировщика'
 'Нарушение требований сигналов светофора'
 'Нарушение требований сигналов светофора, Нарушение требований дорожных знаков'
 'Нарушение требований сигналов светофора, Непредоставление преимущества в движении пешеходу'
 'Нарушение требований сигналов светофора, Несоответствие скорости конкретным условиям движения'
 'Нарушение требований сигналов светофора, Превышение установленной скорости движения'
 'Нахождение на проезжей части без цели её перехода'
 'Невыполнение требований обеспечения безопасности при начале движения'
 'Невыполнение требований обеспечения безопасности при начале движения, Нарушение правил перевозки людей'
 'Невыполнение требований обеспечения безопасности при начале движения, Непредоставление преимущества в движении пешеходу'
 'Неожиданный выход из-за стоящего ТС'
 'Неповиновение или сопротивление находящемуся при исполнении служебных обязанностей сотруднику правоохранительных органов или военнослужащему при остановке или задержании ТС'
 'Неподача или неправильная подача сигналов поворота'
 'Неподчинение сигналам регулирования' 'Неправильный выбор дистанции'
 'Неправильный выбор дистанции, Выезд на полосу встречного движения'
 'Неправильный выбор дистанции, Выезд на трамвайные пути встречного направления'
 'Неправильный выбор дистанции, Другие нарушения ПДД водителем'
 'Неправильный выбор дистанции, Нарушение правил перестроения'
 'Неправильный выбор дистанции, Нарушение правил расположения ТС на проезжей части'
 'Неправильный выбор дистанции, Нарушение требований сигналов светофора'
 'Неправильный выбор дистанции, Несоблюдение бокового интервала'
 'Неправильный выбор дистанции, Несоблюдение условий, разрешающих движение транспорта задним ходом'
 'Неправильный выбор дистанции, Несоответствие скорости конкретным условиям движения'
 'Неправильный выбор дистанции, Пересечение велосипедистом проезжей части по пешеходному переходу'
 'Неправильный выбор дистанции, Превышение установленной скорости движения'
 'Неправильный выбор дистанции, Превышение установленной скорости движения, Несоответствие скорости конкретным условиям движения'
 'Непредоставление преимущества в движении ТС, имеющему нанесенные на наружные поверхности специальные цветографические схемы, надписи и обозначения, с одновременно включённым проблесковым маячком синего цвета и специальным звуковым сигналом'
 'Непредоставление преимущества в движении пешеходу'
 'Непредоставление преимущества при пересечении проезжей части вне перекрестка при движении на велосипеде или СИМ'
 'Несоблюдение бокового интервала'
 'Несоблюдение бокового интервала, Другие нарушения ПДД водителем'
 'Несоблюдение бокового интервала, Неправильный выбор дистанции'
 'Несоблюдение бокового интервала, Несоответствие скорости конкретным условиям движения'
 'Несоблюдение бокового интервала, Превышение установленной скорости движения'
 'Несоблюдение очередности проезда'
 'Несоблюдение очередности проезда перекрестков'
 'Несоблюдение очередности проезда перекрестков, Другие нарушения ПДД водителем'
 'Несоблюдение очередности проезда перекрестков, Нарушение требований дорожных знаков'
 'Несоблюдение очередности проезда перекрестков, Нарушение требований линий разметки'
 'Несоблюдение очередности проезда перекрестков, Нарушение требований сигналов светофора'
 'Несоблюдение очередности проезда перекрестков, Нарушение требований сигналов светофора, Нарушение требований дорожных знаков'
 'Несоблюдение очередности проезда перекрестков, Неправильный выбор дистанции'
 'Несоблюдение очередности проезда перекрестков, Несоответствие скорости конкретным условиям движения'
 'Несоблюдение очередности проезда, Выезд на полосу встречного движения'
 'Несоблюдение очередности проезда, Выезд на полосу встречного движения с разворотом, поворотом налево или объездом препятствия'
 'Несоблюдение очередности проезда, Нарушение правил при круговом движении'
 'Несоблюдение очередности проезда, Нарушение правил проезда пешеходного перехода'
 'Несоблюдение очередности проезда, Нарушение требований дорожных знаков'
 'Несоблюдение очередности проезда, Нарушение требований сигналов светофора'
 'Несоблюдение очередности проезда, Неповиновение или сопротивление находящемуся при исполнении служебных обязанностей сотруднику правоохранительных органов или военнослужащему при остановке или задержании ТС'
 'Несоблюдение очередности проезда, Несоответствие скорости конкретным условиям движения'
 'Несоблюдение очередности проезда, Превышение установленной скорости движения'
 'Несоблюдение условий, разрешающих движение транспорта задним ходом'
 'Несоблюдение условий, разрешающих движение транспорта задним ходом, Непредоставление преимущества в движении пешеходу'
 'Несоответствие скорости конкретным условиям движения'
 'Несоответствие скорости конкретным условиям движения, Выезд на полосу встречного движения в местах, где это запрещено'
 'Несоответствие скорости конкретным условиям движения, Другие нарушения ПДД водителем'
 'Несоответствие скорости конкретным условиям движения, Непредоставление преимущества в движении пешеходу'
 'Несоответствие скорости конкретным условиям движения, Несоблюдение бокового интервала'
 'Нет нарушений'
 'Оставление движущегося транспортного средства (выход или выпрыгивание на ходу и т.д.)'
 'Передвижение по проезжей части на скейтборде (роликовых коньках и т.д.)'
 'Пересечение велосипедистом проезжей части по пешеходному переходу'
 'Пересечение велосипедистом, лицом, использующим для передвижения СИМ, или водителем мопеда проезжей части по пешеходному переходу, не спешившись'
 'Переход через проезжую часть вне пешеходного перехода в зоне его видимости либо при наличии в непосредственной близости подземного (надземного) пешеходного перехода'
 'Превышение установленной скорости движения'
 'Превышение установленной скорости движения, Выезд на полосу встречного движения'
 'Превышение установленной скорости движения, Нарушение правил расположения ТС на проезжей части'
 'Превышение установленной скорости движения, Нарушение требований сигналов светофора'
 'Превышение установленной скорости движения, Несоблюдение бокового интервала'
 'Превышение установленной скорости движения, Несоответствие скорости конкретным условиям движения'
 'Разворот в местах, где разворот запрещён'
 'Разворот в местах, где разворот запрещён, Нарушение требований линий разметки, Нарушение правил перестроения'
 'Разворот в местах, где разворот запрещён, Несоблюдение очередности проезда'
 'Создание помех для водителя в управлении транспортным средством'
 'Стоянка на проезжей части или обочине без освещения'
 'Управление велосипедом или СИМ, не держась за руль хотя бы одной рукой (при наличии руля)'
 'Управление велосипедом, не оснащённым светоотражающими элементами'
 'Эксплуатация ТС с техническими неисправностями, при которых запрещается их эксплуатация'
 'Эксплуатация технически неисправного ТС (проставляется в случае ДТП по причине технеисправности)']
Число уникальных значения в столбце npdd:
152

Уникальные значения в столбце sop_npdd:
['Выезд на полосу встречного движения'
 'Выезд на полосу встречного движения в местах, где это запрещено'
 'Выезд на полосу встречного движения с разворотом, поворотом налево или объездом препятствия'
 'Выезд на полосу встречного движения с разворотом, поворотом налево или объездом препятствия, Другие нарушения ПДД водителем'
 'Выезд на полосу встречного движения с разворотом, поворотом налево или объездом препятствия, Нарушение требований линий разметки, Несоблюдение требований ОСАГО'
 'Выезд на полосу встречного движения, Другие нарушения ПДД водителем'
 'Выезд на полосу встречного движения, Нарушение правил перевозки людей, Управление ТС в состоянии алкогольного опьянения'
 'Выезд на полосу встречного движения, Нарушение требований сигналов светофора, Управление ТС в состоянии алкогольного опьянения, Светопропускание стекол менее нормативного'
 'Выезд на полосу встречного движения, Несоблюдение требований ОСАГО'
 'Выезд на полосу встречного движения, Несоответствие скорости конкретным условиям движения'
 'Выезд на полосу встречного движения, Оставление места ДТП'
 'Выезд на полосу встречного движения, Отказ водителя от прохождения медицинского освидетельствования на состояние опьянения'
 'Выезд на полосу встречного движения, Отказ водителя от прохождения медицинского освидетельствования на состояние опьянения, Несоблюдение требований ОСАГО'
 'Выезд на полосу встречного движения, Управление ТС в состоянии алкогольного опьянения'
 'Выезд на полосу встречного движения, Управление ТС лицом, не имеющим права на управление ТС'
 'Выезд на полосу встречного движения, Управление ТС лицом, не имеющим права на управление ТС, Отказ водителя от прохождения медицинского освидетельствования на состояние опьянения, Эксплуатация ТС с техническими неисправностями, при которых запрещается их эксплуатация'
 'Выезд на полосу встречного движения, Управление транспортным средством при наличии неисправностей или условий, при которых эксплуатация транспортного средства запрещена'
 'Выезд на полосу встречного движения, Эксплуатация ТС с техническими неисправностями, при которых запрещается их эксплуатация, Несоблюдение требований ОСАГО'
 'Выезд на полосу встречного движения, Эксплуатация незарегистрированного ТС'
 'Выезд на трамвайные пути встречного направления'
 'Движение во встречном направлении по дороге с односторонним движением'
 'Другие нарушения ПДД водителем'
 'Другие нарушения ПДД водителем, Выезд на полосу встречного движения в местах, где это запрещено'
 'Другие нарушения ПДД водителем, Движение во встречном направлении по дороге с односторонним движением'
 'Другие нарушения ПДД водителем, Нарушение правил движения в жилых зонах'
 'Другие нарушения ПДД водителем, Непредоставление преимущества в движении пешеходу'
 'Другие нарушения ПДД водителем, Отсутствие у водителя документов, предусмотренных законодательными и иными НПА'
 'Другие нарушения ПДД водителем, Пересечение велосипедистом, лицом, использующим для передвижения СИМ, или водителем мопеда проезжей части по пешеходному переходу, не спешившись'
 'Другие нарушения ПДД водителем, Разворот в местах, где разворот запрещён'
 'Иные нарушения'
 'Нарушение водителем правил применения ремней безопасности (ставится в случае, когда не пристегнут водитель)'

In [101]:
# Определяем количество явных дубликатов

uch_data_df.duplicated().sum()

0

In [102]:
# Проверяем количество уникальных значений в столбце с номерами карточек ДТП

uch_data_df['kartid'].nunique()

30605

In [ ]:
#Выгружаем полученные данные об участниках ДТП в таблицу базы данных

logger.info("Выгружаем полученные данные об участниках ДТП в таблицу базы данных")
uch_data_df.to_sql('dtp_uchastnic', con=engine, if_exists='append', index=False, chunksize=500, method='multi')
logger.info("Данные об участниках ДТП успешно выгружены в таблицу базы данных")

___

In [103]:
#DataFrame с дополнительными участниками (из uchInfo)

uch_info_data = []
for i in range(len(dtp_data)):
    for item in dtp_data[i]:
        kart_id = item['KartId']
        if 'uchInfo' in item and item['uchInfo']:
            for uch in item['uchInfo']:
                uch_row = {
                'KartId': kart_id,
                'n_ts': 'N/A',  # Для дополнительных участников нет привязки к ТС
                'K_UCH': uch.get('K_UCH', ''),
                'S_T': uch.get('S_T', ''),
                'POL': uch.get('POL', ''),
                'V_ST': uch.get('V_ST', ''),
                'ALCO': uch.get('ALCO', ''),
                'SAFETY_BELT': 'N/A',  # Для дополнительных участников нет этой информации
                'S_SM': uch.get('S_SM', ''),
                'N_UCH': uch.get('N_UCH', ''),
                'S_SEAT_GROUP': 'N/A',
                'INJURED_CARD_ID': 'N/A',
                # Преобразуем списки нарушений в строки
                'NPDD': ', '.join(uch.get('NPDD', [])) if uch.get('NPDD') else '',
                'SOP_NPDD': ', '.join(uch.get('SOP_NPDD', [])) if uch.get('SOP_NPDD') else ''
            }
                uch_info_data.append(uch_row)
                
uch_info_data_df=pd.DataFrame(uch_info_data)

In [104]:
#Выводим первые 5 строк датафрейма

uch_info_data_df.head()

Empty DataFrame
Columns: []
Index: []

_____

## 10. Вывод<a id='soderjanie_10'></a>

В ходе выполнения проекта по выявлению и анализу взаимосвязей между данными о погодных условиях и ДТП в выбранных городах РФ (Казань и Новосибирск) был разработан автоматизированный pipeline, который:
1. Выполняет парсинг данных о всех городах РФ с веб-страницы сайта Wiki с применением инструментов библиотеки Beautiful Soup; 
2. Добавляет координаты к данным о городах (с помощью геокодера Nominatim);
3. Выполняет парсинг данных о погоде через API с сайта open-meteo.com за период с 01.01.2016 по 31.12.2025;
4. Получает коды ОКАТО регионов РФ через API с сайта gibdd.ru;
5. Скачивает карточки ДТП через API с сайта gibdd.ru за период с 01.01.2016 по 31.12.2025;
6. Проводит нормализацию и обработку данных;
7. Загружает полученную информацию в базу данных: в виде промежуточных буферных таблиц с необработанными данными, полученными сразу после скачивания, и финальных таблиц с нормализованными данными.

В результате в базе данных сохранены следующие таблицы с обработанными данными:
- **'cities'**: содержит информацию о городах РФ с их координатами;
- **'codes_oktmo'**: содержит информацию о кодах ОКТМО регионов и муниципалитетов РФ;
- **'weather'**: содержит информацию о погоде в Казани и Новосибирске по часам за период с 01.01.2016 по 31.12.2025; 
- **'dtp_common'**: содержит общую информацию о ДТП в Казани и Новосибирске за период с 01.01.2016 по 31.12.2025;
- **'dtp_info'**: содержит дополнительную информацию о месте и условиях ДТП в Казани и Новосибирске за период с 01.01.2016 по 31.12.2025;
- **'dtp_transp_sr'**: содержит информацию о транспортных средствах, участвующих в ДТП в Казани и Новосибирске за период с 01.01.2016 по 31.12.2025;
- **'dtp_uchastnic'**: содержит информацию об участниках ДТП в Казани и Новосибирске за период с 01.01.2016 по 31.12.2025.

Информации о дополнительных участниках в Казани и Новосибирске за период с 01.01.2016 по 31.12.2025 отсутствует.